(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function stamp(){return new Date().toISOString().replace(/[:.]/g,'-')}
function download(name,text,type='application/json'){const blob=new Blob([text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function safeClone(){return JSON.parse(JSON.stringify(db))}
function companyLabel(){try{return typeof company==='function'?(company()?.name||'OfficeOS'):'OfficeOS'}catch{return'OfficeOS'}}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
function toCsv(rows){if(!rows.length)return'';const keys=[...new Set(rows.flatMap(x=>Object.keys(x||{})))];return [keys.map(csvCell).join(','),...rows.map(r=>keys.map(k=>csvCell(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(','))].join('\n')}
window.officeExportBackup=function(){const payload={format:'officeos-backup',version:1,exportedAt:new Date().toISOString(),accountEmail:currentUser?.email||'',data:safeClone()};download(`OfficeOS-backup-${stamp()}.json`,JSON.stringify(payload,null,2));try{logActivity(current()==='all'?(db.companies[0]?.id||''):current(),'Exported full OfficeOS backup');save()}catch{}}
window.officeExportCsvBundle=function(){const groups=['companies','customers','leads','jobs','events','tasks','invoices','approvals','activity','employees','timeEntries','payrollRuns'];for(const key of groups){const rows=Array.isArray(db[key])?db[key]:[];if(rows.length)download(`OfficeOS-${key}-${stamp()}.csv`,toCsv(rows),'text/csv;charset=utf-8')}alert('CSV exports created for the data currently stored in OfficeOS.')}
window.officeRestoreBackup=function(){let input=document.getElementById('officeBackupFile');if(!input){input=document.createElement('input');input.id='officeBackupFile';input.type='file';input.accept='.json,application/json';input.style.display='none';document.body.appendChild(input);input.addEventListener('change',async()=>{const file=input.files?.[0];input.value='';if(!file)return;try{const parsed=JSON.parse(await file.text());const incoming=parsed?.format==='officeos-backup'?parsed.data:parsed;if(!incoming||typeof incoming!=='object'||!Array.isArray(incoming.companies))throw new Error('This does not look like an OfficeOS backup.');if(!confirm('Restore this OfficeOS backup? This will replace the business data currently loaded in your account.'))return;db=typeof migrate==='function'?migrate(incoming):incoming;localStorage.setItem(typeof KEY==='string'?KEY:'officeos_v6',JSON.stringify(db));if(typeof cloudSave==='function')await cloudSave();if(typeof render==='function')render();window.renderSettingsPage?.();alert('OfficeOS backup restored successfully.')}catch(e){alert('Could not restore this backup: '+(e?.message||'Invalid backup file.'))}})}input.click()}
function markup(){return `<details class="settings-accordion" id="sg-data"><summary><span class="settings-icon">💾</span><span><b>Data & Backup</b><small>Export or restore your OfficeOS information</small></span><span class="settings-chevron">›</span></summary><div class="settings-accordion-body"><p class="muted">Create a complete OfficeOS backup before major changes, or export spreadsheet-friendly CSV copies of your business records.</p><button type="button" class="secondary full" onclick="officeExportBackup()">Download Full Backup</button><button type="button" class="secondary full" style="margin-top:8px" onclick="officeExportCsvBundle()">Export CSV Copies</button><button type="button" class="secondary full" style="margin-top:8px" onclick="officeRestoreBackup()">Restore From Backup</button><p class="muted" style="margin-top:10px;font-size:12px">Backups may contain customer and financial information. Store them somewhere private.</p></div></details>`}
function install(){const shell=document.querySelector('#settingsHome .settings-shell');if(!shell||document.getElementById('sg-data'))return;const saveBtn=[...shell.querySelectorAll('button')].find(b=>/save all settings/i.test(b.textContent||''));if(saveBtn)saveBtn.insertAdjacentHTML('beforebegin',markup());const jump=shell.querySelector('.settings-jump');if(jump&&!jump.querySelector('[data-settings-data]')){const b=document.createElement('button');b.type='button';b.dataset.settingsData='1';b.textContent='💾 Data';b.onclick=()=>window.openSettingsGroup?.('data');jump.appendChild(b)}}
const old=window.renderSettingsPage;window.renderSettingsPage=function(){const r=old?.apply(this,arguments);setTimeout(install,0);return r};setTimeout(install,1200);
})();