(function(){
'use strict';
const SYN={
 name:['officeos full name','customer name','name','display name','full name','billing name','company name'],email:['email','email address','customer email'],phone:['phone','phone number','mobile','mobile phone','telephone'],address:['officeos full address','billing address','address','street','customer address'],notes:['note','notes','memo','customer note','tags'],service:['service','product','job type','service requested'],value:['value','estimated value','estimate','estimate amount','potential value'],status:['status','customer status','lead status','job status','invoice status'],customer:['customer','customer name','client','bill to','display name'],title:['job','job name','service','description','product'],amount:['amount','total','total amount','balance','open balance','total spent','grand total'],date:['date','job date','scheduled date','service date'],time:['time','scheduled time'],number:['invoice #','invoice no','invoice number','number','doc number'],issueDate:['issue date','invoice date','date'],dueDate:['due date','due']
};
let queue=[];
const n=v=>String(v??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const esc2=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function cid(){return typeof current==='function'&&current()!=='all'?current():(db.companies?.[0]?.id||'')}
function sourceFrom(headers){const h=headers.map(n);if(h.includes('first name')&&h.includes('last name')&&h.some(x=>x.includes('total spent')))return'Shopify';if(h.some(x=>x.includes('open balance'))||h.some(x=>x.includes('invoice no'))||h.some(x=>x.includes('customer full name')))return'QuickBooks';return'Generic'}
function targetFrom(headers,name=''){const h=headers.map(n),fn=n(name);if(fn.includes('invoice')||h.some(x=>x.includes('invoice'))&&(h.includes('amount')||h.includes('total')||h.includes('balance')))return'invoices';if(fn.includes('job')||h.some(x=>x.includes('job'))||h.some(x=>x.includes('scheduled date')))return'jobs';if(fn.includes('lead')||h.some(x=>x.includes('lead status'))||h.some(x=>x.includes('estimate amount')))return'leads';return'customers'}
function prep(rows){return rows.map(r=>{const x={...r};const key=k=>Object.keys(r).find(h=>n(h)===k),first=key('first name'),last=key('last name');if(first||last)x['OfficeOS Full Name']=[r[first]||'',r[last]||''].join(' ').trim();const parts=['address1','address2','city','province','state','zip','postal code','country'].map(k=>{const h=key(k);return h?r[h]:''}).filter(Boolean);if(parts.length)x['OfficeOS Full Address']=parts.join(', ');return x})}
function pick(row,field){const keys=Object.keys(row),norm=keys.map(k=>[k,n(k)]);for(const syn of SYN[field]||[field]){const s=n(syn),m=norm.find(([,h])=>h===s)||norm.find(([,h])=>h.includes(s)||s.includes(h));if(m)return String(row[m[0]]??'').trim()}return''}
function num(v){const x=Number(String(v||'').replace(/[$,%]/g,'').replace(/,/g,''));return Number.isFinite(x)?x:0}
function makeRecord(row,item,batchId){const company=cid(),now=nowISO(),base={id:uid(),company,createdAt:now,updatedAt:now,importedAt:now,importBatchId:batchId,sourceSystem:item.source};if(item.target==='customers')return{...base,name:pick(row,'name')||'Imported Customer',email:pick(row,'email'),phone:pick(row,'phone'),address:pick(row,'address'),notes:pick(row,'notes')};if(item.target==='leads')return{...base,name:pick(row,'name')||'Imported Lead',email:pick(row,'email'),phone:pick(row,'phone'),service:pick(row,'service'),value:Math.max(0,num(pick(row,'value'))),status:['New','Contacted','Estimate Scheduled','Estimate Sent','Won','Lost'].includes(pick(row,'status'))?pick(row,'status'):'New',notes:pick(row,'notes'),initialEmailSuppressed:true};if(item.target==='jobs')return{...base,customer:pick(row,'customer')||pick(row,'name')||'Imported Customer',title:pick(row,'title')||'Imported Job',address:pick(row,'address'),amount:Math.max(0,num(pick(row,'amount'))),status:['Scheduled','In Progress','Waiting','Complete','Cancelled'].includes(pick(row,'status'))?pick(row,'status'):'Scheduled',date:pick(row,'date'),time:pick(row,'time'),notes:pick(row,'notes')};return{...base,customer:pick(row,'customer')||pick(row,'name')||'Imported Customer',email:pick(row,'email'),type:'Invoice',number:pick(row,'number'),issueDate:pick(row,'issueDate'),dueDate:pick(row,'dueDate'),status:['Draft','Sent','Open','Overdue','Paid'].includes(pick(row,'status'))?pick(row,'status'):'Open',amount:Math.max(0,num(pick(row,'amount'))),lines:[{description:'Imported invoice balance',qty:1,rate:Math.max(0,num(pick(row,'amount')))}],taxRate:0,notes:pick(row,'notes'),paymentUrl:''}}
function blank(rec,target){if(target==='customers'||target==='leads')return!rec.name||/^Imported (Customer|Lead)$/.test(rec.name);return!rec.customer}
function dup(rec,target){const company=rec.company;if(target==='customers')return(db.customers||[]).some(x=>x.company===company&&((rec.email&&n(x.email)===n(rec.email))||(rec.phone&&n(x.phone)===n(rec.phone))||(n(x.name)===n(rec.name)&&rec.address&&n(x.address)===n(rec.address))));if(target==='leads')return(db.leads||[]).some(x=>x.company===company&&((rec.email&&n(x.email)===n(rec.email))||(rec.phone&&n(x.phone)===n(rec.phone))||(n(x.name)===n(rec.name)&&n(x.service)===n(rec.service))));if(target==='jobs')return(db.jobs||[]).some(x=>x.company===company&&n(x.customer)===n(rec.customer)&&n(x.title)===n(rec.title)&&String(x.date||'')===String(rec.date||''));return(db.invoices||[]).some(x=>x.company===company&&rec.number&&n(x.number)===n(rec.number))}
async function parse(file){if(!window.XLSX)throw new Error('Spreadsheet reader is still loading.');const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),sheet=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false});if(!raw.length)throw new Error('No rows found');const rows=prep(raw),headers=Object.keys(rows[0]);return{file,name:file.name,rows,headers,source:sourceFrom(headers),target:targetFrom(headers,file.name),error:''}}
function summary(item){let ready=0,duplicates=0,invalid=0;for(const row of item.rows){const rec=makeRecord(row,item,'preview');if(blank(rec,item.target))invalid++;else if(dup(rec,item.target))duplicates++;else ready++}return{ready,duplicates,invalid,total:item.rows.length}}
function render(){const box=document.getElementById('batchImportQueue'),run=document.getElementById('batchImportRun');if(!box)return;if(!queue.length){box.innerHTML='<div class="muted">Choose several export files at once. They will appear here before anything is imported.</div>';if(run)run.disabled=true;return}let total=0;box.innerHTML=queue.map((x,i)=>{if(x.error)return`<div class="import-batch"><b>${esc2(x.name)}</b><div class="muted">Could not read: ${esc2(x.error)}</div><button class="secondary" onclick="OfficeOSBatchImport.remove(${i})">Remove</button></div>`;const s=summary(x);total+=s.ready;return`<div class="import-batch"><div class="row between"><div><b>${esc2(x.name)}</b><div class="muted">${esc2(x.source)} · detected as ${esc2(x.target)} · ${s.total.toLocaleString()} rows</div><div class="muted">${s.ready.toLocaleString()} ready · ${s.duplicates.toLocaleString()} duplicates · ${s.invalid.toLocaleString()} incomplete</div></div><button class="secondary" onclick="OfficeOSBatchImport.remove(${i})">Remove</button></div></div>`}).join('');if(run){run.disabled=!total||!cid();run.textContent=total?`Import ${total.toLocaleString()} Records`:'Import All Files'}}
async function select(files){queue=[];const list=[...files];const status=document.getElementById('batchImportStatus');if(status)status.textContent=`Reading ${list.length} file${list.length===1?'':'s'}…`;for(const file of list){try{queue.push(await parse(file))}catch(e){queue.push({name:file.name,error:e.message||'Unreadable file',rows:[]})}}if(status)status.textContent=`${list.length} file${list.length===1?'':'s'} ready for review.`;render()}
async function run(){if(!cid())return alert('Choose an OfficeOS company first.');if(!queue.length)return;const readable=queue.filter(x=>!x.error);if(!readable.length)return alert('None of the selected files could be read.');if(!confirm(`Import all ${readable.length} readable files into this company? OfficeOS will skip likely duplicates and incomplete rows.`))return;let added=0,duplicates=0,invalid=0;for(const item of readable){let itemDuplicates=0,itemInvalid=0;const batchId='imp_'+uid(),ids=[];for(const row of item.rows){const rec=makeRecord(row,item,batchId);if(blank(rec,item.target)){invalid++;itemInvalid++;continue}if(dup(rec,item.target)){duplicates++;itemDuplicates++;continue}db[item.target]=db[item.target]||[];db[item.target].push(rec);ids.push(rec.id);added++;if(item.target==='jobs'&&typeof syncJobEvent==='function')syncJobEvent(rec)}db.importBatches=Array.isArray(db.importBatches)?db.importBatches:[];db.importBatches.unshift({id:batchId,company:cid(),target:item.target,source:item.source,fileName:item.name,createdAt:nowISO(),recordIds:ids,rowCount:item.rows.length,duplicatesSkipped:itemDuplicates,invalidSkipped:itemInvalid})}logActivity(cid(),`Batch imported ${added} records from ${readable.length} files`);save();if(typeof cloudSave==='function')await cloudSave();queue=[];render();alert(`Batch import complete. ${added} records added. ${duplicates} duplicates and ${invalid} incomplete rows skipped.`)}
function install(){const center=document.getElementById('officeImportCenter');if(!center||document.getElementById('batchImportCard'))return;const card=document.createElement('div');card.id='batchImportCard';card.className='batch-import-box';card.innerHTML=`<div class="migration-divider"><span>FASTEST: IMPORT MULTIPLE FILES</span></div><p class="muted">Have separate customer, invoice, lead or job exports? Select them all together. OfficeOS will detect each file and review the whole batch before importing.</p><input id="batchImportFiles" type="file" multiple accept=".csv,.xlsx,.xls,text/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" style="display:none"><label for="batchImportFiles" class="import-file-cta"><b>Choose All Export Files</b><span>Select multiple CSV, XLS or XLSX files at the same time</span></label><div id="batchImportStatus" class="muted" style="margin-top:8px"></div><div id="batchImportQueue" style="margin-top:10px"></div><button id="batchImportRun" type="button" class="primary full" disabled style="margin-top:12px">Import All Files</button>`;const divider=center.querySelector('.migration-divider');if(divider)center.insertBefore(card,divider);else center.appendChild(card);document.getElementById('batchImportFiles').addEventListener('change',e=>select(e.target.files));document.getElementById('batchImportRun').addEventListener('click',run);render()}
window.OfficeOSBatchImport={select,run,remove(i){queue.splice(i,1);render()},queue:()=>queue};
setTimeout(install,1300);
})();