let calendarCursor=new Date();
let calendarMode="month";
function calendarDateKey(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return `${y}-${m}-${day}`}
function calendarMonthTitle(){return calendarCursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}
function changeCalendarMonth(delta){calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+delta,1);renderCalendar()}
function goCalendarToday(){calendarCursor=new Date();renderCalendar()}
function setCalendarMode(mode){calendarMode=mode;renderCalendar()}
function calendarOpenDay(key){const events=relevant(db.events).filter(x=>x.date===key).sort((a,b)=>(a.time||"").localeCompare(b.time||""));const pretty=dateText(key);formTitle.textContent=pretty;formBody.innerHTML=events.length?events.map(eventCard).join("")+`<button class="primary full" style="margin-top:12px" onclick="closeForm();openForm('event',{date:'${key}'})">+ Add Event</button>`:`<div class="empty">Nothing scheduled.</div><button class="primary full" onclick="closeForm();openForm('event',{date:'${key}'})">+ Add Event</button>`;overlay.classList.add("open")}
function renderMonthGrid(){const first=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1);const last=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,0);const start=first.getDay();const todayKey=calendarDateKey(new Date());const events=relevant(db.events);const byDate={};for(const e of events)(byDate[e.date]||(byDate[e.date]=[])).push(e);let html=`<div class="calendar-toolbar"><button class="secondary cal-arrow" onclick="changeCalendarMonth(-1)">‹</button><div class="calendar-title">${calendarMonthTitle()}</div><button class="secondary cal-arrow" onclick="changeCalendarMonth(1)">›</button></div><div class="calendar-actions"><button class="secondary" onclick="goCalendarToday()">Today</button><div class="calendar-toggle"><button class="${calendarMode==='month'?'primary':'secondary'}" onclick="setCalendarMode('month')">Month</button><button class="${calendarMode==='list'?'primary':'secondary'}" onclick="setCalendarMode('list')">List</button></div></div><div class="calendar-grid weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid month-grid">`;
for(let i=0;i<start;i++)html+='<div class="cal-day outside"></div>';
for(let day=1;day<=last.getDate();day++){const d=new Date(first.getFullYear(),first.getMonth(),day),key=calendarDateKey(d),items=byDate[key]||[];html+=`<button class="cal-day ${key===todayKey?'today':''} ${items.length?'has-events':''}" onclick="calendarOpenDay('${key}')"><span class="day-num">${day}</span><span class="event-dots">${items.slice(0,3).map(e=>`<i title="${esc(e.title)}"></i>`).join('')}</span>${items.length?`<span class="event-count">${items.length}</span>`:''}</button>`}
const cells=start+last.getDate(),tail=(7-(cells%7))%7;for(let i=0;i<tail;i++)html+='<div class="cal-day outside"></div>';html+='</div>';
const upcoming=events.filter(x=>x.date&&x.date>=calendarDateKey(new Date())).sort((a,b)=>((a.date||'')+(a.time||'')).localeCompare((b.date||'')+(b.time||''))).slice(0,5);html+=`<div class="calendar-upcoming"><h2>Upcoming</h2>${upcoming.length?upcoming.map(x=>`<div class="mini-event" onclick="editItem('event','${x.id}')"><div><b>${esc(x.title)}</b><div class="muted">${dateText(x.date)}${x.time?` • ${esc(x.time)}`:''}${x.customer?` • ${esc(x.customer)}`:''}</div></div></div>`).join(''):'<div class="empty">Nothing upcoming.</div>'}</div>`;return html}
function renderCalendarList(){const a=[...relevant(db.events)].sort((x,y)=>((x.date||"")+(x.time||"")).localeCompare((y.date||"")+(y.time||"")));let html=`<div class="calendar-actions"><button class="secondary" onclick="goCalendarToday()">Today</button><div class="calendar-toggle"><button class="${calendarMode==='month'?'primary':'secondary'}" onclick="setCalendarMode('month')">Month</button><button class="${calendarMode==='list'?'primary':'secondary'}" onclick="setCalendarMode('list')">List</button></div></div>`;if(!a.length)return html+'<div class="empty">Nothing scheduled yet.</div>';let last="";for(const x of a){if(x.date!==last){html+=`<div class="section-title" style="margin-top:16px"><h2>${dateText(x.date)}</h2></div>`;last=x.date}html+=eventCard(x)}return html}
function renderCalendar(){const box=$("calendarList");if(!box)return;box.innerHTML=calendarMode==="month"?renderMonthGrid():renderCalendarList()}
