(function(){
'use strict';
const el=id=>document.getElementById(id);
const escC=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let filter='all';
function ensure(){db.communicationHistory=Array.isArray(db.communicationHistory)?db.communicationHistory:[];db.communicationHandled=Array.isArray(db.communicationHandled)?db.communicationHandled:[]}
function cid(){return typeof current==='function'?current():'all'}
function relevant2(list){const c=cid();return c==='all'?(list||[]):(list||[]).filter(x=>x.company===c)}
function customerFor(name,companyId){const n=String(name||'').trim().toLowerCase();return(db.customers||[]).find(c=>c.company===companyId&&String(c.name||'').trim().toLowerCase()===n)||null}
function contact(x){if(x.kind==='lead')return{email:x.record.email||'',phone:x.record.phone||'',name:x.record.name||''};const c=customerFor(x.customer,x.company);return{email:x.record.email||c?.email||'',phone:x.record.phone||c?.phone||'',name:x.customer||c?.name||''}}
function companyLabel(companyId){return(db.companies||[]).find(c=>c.id===companyId)?.name||'OfficeOS'}
function daysBetween(a,b){return Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)}
function handledKey(item){return `${item.kind}:${item.id}:${item.state}`}
function isHandled(item){return db.communicationHandled.includes(handledKey(item))}
function attention(){ensure();const today=new Date().toISOString().slice(0,10),tom=new Date();tom.setDate(tom.getDate()+1);const tomorrow=tom.toISOString().slice(0,10),out=[];
 for(const inv of relevant2(db.invoices||[])){if(inv.type!=='Invoice'||inv.status==='Paid')continue;const due=inv.dueDate||'';if(inv.status==='Overdue'||(due&&due<today)){out.push({kind:'invoice',id:inv.id,company:inv.company,customer:inv.customer||'Customer',record:inv,state:`${inv.status}:${due}:${inv.amount}`,priority:1,title:`${inv.customer||'Customer'} has an overdue invoice`,detail:`${money(inv.amount)}${due?' · due '+dateText(due):''}`,category:'Invoices'})}}
 for(const lead of relevant2(db.leads||[])){if(['Won','Lost'].includes(lead.status))continue;const updated=(lead.updatedAt||lead.createdAt||'').slice(0,10),age=updated?daysBetween(updated,today):0;if(lead.status==='Estimate Sent'&&age>=2)out.push({kind:'lead',id:lead.id,company:lead.company,customer:lead.name,record:lead,state:`${lead.status}:${updated}`,priority:2,title:`Follow up with ${lead.name}`,detail:`Estimate sent${lead.value?` · ${money(lead.value)}`:''}${age?` · ${age} days ago`:''}`,category:'Leads'});else if(lead.status==='New'&&age>=1)out.push({kind:'lead',id:lead.id,company:lead.company,customer:lead.name,record:lead,state:`${lead.status}:${updated}`,priority:3,title:`New lead waiting: ${lead.name}`,detail:`${lead.service||'New inquiry'}${age?` · waiting ${age} day${age===1?'':'s'}`:''}`,category:'Leads'})}
 for(const event of relevant2(db.events||[])){if(event.date!==tomorrow)continue;if(!event.customer)continue;out.push({kind:'event',id:event.id,company:event.company,customer:event.customer,record:event,state:`${event.date}:${event.time}:${event.title}`,priority:4,title:`Confirm tomorrow with ${event.customer}`,detail:`${event.type||'Appointment'} · ${dateText(event.date)}${event.time?' · '+event.time:''}`,category:'Upcoming'})}
 return out.filter(x=>!isHandled(x)).sort((a,b)=>a.priority-b.priority).slice(0,30)}
function message(item){const c=contact(item),business=companyLabel(item.company);if(item.kind==='invoice')return{subject:`Invoice reminder from ${business}`,body:`Hi ${c.name||'there'},\n\nJust a friendly reminder from ${business} about your outstanding invoice for ${money(item.record.amount)}${item.record.dueDate?`, due ${dateText(item.record.dueDate)}`:''}. Please let us know if you have any questions.\n\nThank you,\n${business}`};if(item.kind==='lead')return{subject:`Following up from ${business}`,body:`Hi ${c.name||'there'},\n\nI wanted to follow up regarding ${item.record.service||'your project'} and see if you have any questions or would like to take the next step.\n\nThank you,\n${business}`};return{subject:`Confirming your ${item.record.type||'appointment'} with ${business}`,body:`Hi ${c.name||'there'},\n\nJust confirming your ${String(item.record.type||'appointment').toLowerCase()} with ${business} for ${dateText(item.record.date)}${item.record.time?` at ${item.record.time}`:''}. Please let us know if anything has changed.\n\nThank you,\n${business}`}}
function findItem(kind,id){return attention().find(x=>x.kind===kind&&x.id===id)||(()=>{const map={invoice:'invoices',lead:'leads',event:'events'},r=(db[map[kind]]||[]).find(x=>x.id===id);if(!r)return null;return{kind,id,company:r.company,customer:r.customer||r.name||'',record:r,state:'manual'}})()}
function openItem(kind,id){if(kind==='lead'){document.querySelector('nav button[data-page="leads"]')?.click();setTimeout(()=>editItem?.('lead',id),120);return}if(kind==='event'){document.querySelector('nav button[data-page="calendar"]')?.click();setTimeout(()=>editItem?.('event',id),120);return}if(kind==='invoice'){document.querySelector('nav button[data-page="more"]')?.click();setTimeout(()=>{window.officeJumpTo?.('money');setTimeout(()=>editItem?.('invoice',id),120)},80)}}
function log(kind,item,channel){ensure();db.communicationHistory.unshift({id:uid(),company:item.company,kind,recordId:item.id,customer:item.customer||'',channel,createdAt:nowISO()});db.communicationHistory=db.communicationHistory.slice(0,100);logActivity(item.company,`${channel} opened for ${item.customer||'customer'}`);save()}
function compose(kind,id,channel){const item=findItem(kind,id);if(!item)return alert('That record is no longer available.');const c=contact(item),m=message(item);if(channel==='email'){if(!c.email)return alert('Add an email address for this customer first.');log(kind,item,'Email');location.href=`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(m.subject)}&body=${encodeURIComponent(m.body)}`;return}if(!c.phone)return alert('Add a phone number for this customer first.');log(kind,item,'Text');location.href=`sms:${encodeURIComponent(c.phone)}&body=${encodeURIComponent(m.body.replace(/\n+/g,' '))}`}
async function sendInvoice(id){const inv=(db.invoices||[]).find(x=>x.id===id);if(!inv)return alert('Invoice not found.');const item=findItem('invoice',id),c=item?contact(item):{email:''};if(!inv.email&&c.email){inv.email=c.email;inv.updatedAt=nowISO();save()}if(typeof window.emailInvoice!=='function')return alert('Invoice email service is still loading. Try again in a moment.');const result=await window.emailInvoice(id);if(result?.ok){const live=findItem('invoice',id);if(live){ensure();const k=handledKey(live);if(!db.communicationHandled.includes(k))db.communicationHandled.push(k);save();render()}}}
function markHandled(kind,id){const item=findItem(kind,id);if(!item)return;ensure();const key=handledKey(item);if(!db.communicationHandled.includes(key))db.communicationHandled.push(key);db.communicationHistory.unshift({id:uid(),company:item.company,kind,recordId:id,customer:item.customer||'',channel:'Handled',createdAt:nowISO()});logActivity(item.company,`Communication handled: ${item.title||item.customer||kind}`);save();render()}
function buttons(item){const c=contact(item),b=[];b.push(`<button class="secondary" onclick="officeCommOpen('${item.kind}','${item.id}')">Open</button>`);if(item.kind==='invoice'&&c.email)b.push(`<button class="primary" onclick="officeCommSendInvoice('${item.id}')">Send Invoice</button>`);else if(c.email)b.push(`<button class="secondary" onclick="officeCommCompose('${item.kind}','${item.id}','email')">Email</button>`);if(c.phone)b.push(`<button class="secondary" onclick="officeCommCompose('${item.kind}','${item.id}','text')">Text</button>`);b.push(`<button class="secondary" onclick="officeCommHandled('${item.kind}','${item.id}')">Handled</button>`);return b.join('')}
function card(item){const icon=item.kind==='invoice'?'$':item.kind==='lead'?'◎':'◷';return `<div class="comm-item"><div class="comm-icon">${icon}</div><div class="comm-main"><div class="row between"><div><b>${escC(item.title)}</b><div class="muted">${escC(item.detail)}</div></div><span class="tag">${escC(item.category)}</span></div><div class="comm-actions">${buttons(item)}</div></div></div>`}
function history(){const c=cid(),h=(db.communicationHistory||[]).filter(x=>c==='all'||x.company===c).slice(0,8);return h.length?h.map(x=>`<div class="comm-history-row"><div><b>${escC(x.customer||x.kind)}</b><span>${escC(x.channel)}</span></div><time>${new Date(x.createdAt).toLocaleString()}</time></div>`).join(''):'<div class="empty">No communication activity yet.</div>'}
function render(){ensure();const host=el('communicationsCenter');if(!host)return;const all=attention(),items=filter==='all'?all:all.filter(x=>x.category.toLowerCase()===filter);host.innerHTML=`<div class="card comm-card"><div class="row between"><div><div class="kicker">Communications</div><h2>Needs Follow-up</h2></div><span class="comm-count">${all.length}</span></div><p class="muted">OfficeOS collects customer communication that needs attention so it does not get lost between leads, jobs, calendar and invoices.</p><div class="comm-filters"><button class="${filter==='all'?'active':''}" onclick="officeCommFilter('all')">All</button><button class="${filter==='invoices'?'active':''}" onclick="officeCommFilter('invoices')">Invoices</button><button class="${filter==='leads'?'active':''}" onclick="officeCommFilter('leads')">Leads</button><button class="${filter==='upcoming'?'active':''}" onclick="officeCommFilter('upcoming')">Upcoming</button></div><div class="comm-list">${items.length?items.map(card).join(''):'<div class="empty">Nothing in this communication queue right now.</div>'}</div><details class="comm-history"><summary>Recent communication activity</summary>${history()}</details></div>`;window.refreshOfficeOrganization?.()}
function mount(){ensure();const office=el('more');if(!office||el('communicationsSection'))return render();const section=document.createElement('div');section.id='communicationsSection';section.innerHTML='<div id="communicationsCenter"></div>';const approvals=[...office.querySelectorAll('.card')].find(c=>/^Approvals$/i.test(c.querySelector('h2')?.textContent||''));if(approvals)approvals.insertAdjacentElement('beforebegin',section);else office.appendChild(section);render();window.refreshOfficeOrganization?.()}
window.officeCommOpen=openItem;window.officeCommCompose=compose;window.officeCommSendInvoice=sendInvoice;window.officeCommHandled=markHandled;window.officeCommFilter=function(v){filter=v;render()};window.renderCommunications=render;
document.getElementById('companySelect')?.addEventListener('change',()=>setTimeout(render,0));setTimeout(mount,1500);const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(mount,0);setTimeout(render,20);return r};
})();