(function(){
'use strict';
const ENDPOINT='https://bowrytgqbunodtmzvabp.supabase.co/functions/v1/officeos-customer-wallet';
const el=id=>document.getElementById(id);let stripeClient=null,elements=null,walletCtx=null;
function customerForInvoice(inv){const n=String(inv?.customer||'').trim().toLowerCase();return(db.customers||[]).find(c=>c.company===inv.company&&String(c.name||'').trim().toLowerCase()===n)||null}
function customerRef(c,inv){return c?.id||`invoice-customer:${inv?.company||''}:${String(inv?.customer||'').trim().toLowerCase()}`}
async function call(body){const {data:{session},error}=await supabaseClient.auth.getSession();if(error||!session?.access_token)throw new Error('Please sign in again.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Payment request failed.');return d}
function loadStripeJs(){return new Promise((resolve,reject)=>{if(window.Stripe)return resolve(window.Stripe);let s=document.querySelector('script[data-office-stripe-js]');if(s){s.addEventListener('load',()=>resolve(window.Stripe));s.addEventListener('error',reject);return}s=document.createElement('script');s.src='https://js.stripe.com/v3/';s.async=true;s.dataset.officeStripeJs='1';s.onload=()=>resolve(window.Stripe);s.onerror=reject;document.head.appendChild(s)})}
function context(inv){const c=customerForInvoice(inv);return{invoice:inv,customer:c,customerRef:customerRef(c,inv),customerName:c?.name||inv.customer||'Customer',customerEmail:c?.email||inv.email||'',companyRef:inv.company}}
const today=()=>new Date().toISOString().slice(0,10);function currentBalance(inv){return Math.max(0,Number(inv.balanceDue??inv.amount||0))}
function baseHead(ctx){const inv=ctx.invoice;return`<div class="item"><div class="row between"><div><b>${esc(inv.number||'Invoice')}</b><div class="muted">${esc(ctx.customerName)}</div></div><div style="text-align:right"><b>${money(inv.amount)}</b><div class="muted">Balance ${money(currentBalance(inv))}</div></div></div></div>`}
window.officeWalletCurrent=()=>walletCtx;
window.officeTakePayment=function(id){const inv=(db.invoices||[]).find(x=>x.id===id&&String(x.type||'Invoice')==='Invoice');if(!inv)return alert('Invoice not found.');walletCtx=context(inv);formTitle.textContent='Take Payment';formBody.innerHTML=`${baseHead(walletCtx)}<div class="take-pay-grid"><button class="primary" onclick="officeWalletSavedCards()">Saved Card</button><button class="secondary" onclick="officeWalletAddCard()">+ New Card</button><button class="secondary" onclick="officeTerminalOpen()">In-Person Card</button><button class="secondary" onclick="officeWalletManual('Cash')">Cash</button><button class="secondary" onclick="officeWalletManual('Check')">Check</button></div><div id="walletBody"><p class="muted" style="margin-top:14px">Choose how the customer is paying. Card numbers are handled securely by Stripe and are never stored in OfficeOS.</p></div>`;overlay.classList.add('open')};
window.officeWalletManual=function(method){if(!walletCtx)return;const inv=walletCtx.invoice,box=el('walletBody');box.innerHTML=`<label>${method} Amount</label><input id="payRecAmount" type="number" min="0.01" step="0.01" value="${currentBalance(inv).toFixed(2)}"><label>Date Received</label><input id="payRecDate" type="date" value="${today()}"><input id="payRecMethod" type="hidden" value="${method}"><label>${method==='Check'?'Check Number / Memo':'Receipt / Notes'}</label><input id="payRecNotes" placeholder="${method==='Check'?'Check #1234':'Optional note'}"><div class="muted" style="font-size:12px;margin:9px 0">${method==='Check'?'This records the check as received. It does not electronically deposit the check.':'This records cash received and reconciles it against the invoice.'}</div><button class="primary full" onclick="officeSaveRecordedPayment('${inv.id}')">Record ${method} Payment</button>`};
window.officeWalletSavedCards=async function(){if(!walletCtx)return;const box=el('walletBody');box.innerHTML='<div class="empty">Loading saved cards…</div>';try{const d=await call({action:'sync',companyRef:walletCtx.companyRef,customerRef:walletCtx.customerRef,customerName:walletCtx.customerName,customerEmail:walletCtx.customerEmail});if(!d.methods?.length){box.innerHTML='<div class="empty">No saved cards yet.</div><button class="primary full" onclick="officeWalletAddCard()">Add Customer Card</button>';return}box.innerHTML=`<label>Amount to Charge</label><input id="walletChargeAmount" type="number" min="0.01" step="0.01" value="${currentBalance(walletCtx.invoice).toFixed(2)}"><div class="wallet-card-list">${d.methods.map(pm=>`<button class="wallet-card" onclick="officeWalletCharge('${pm.id}')"><span><b>${String(pm.brand||'Card').toUpperCase()} •••• ${pm.last4||''}</b><small>Expires ${pm.expMonth||''}/${pm.expYear||''}</small></span><strong>Charge</strong></button>`).join('')}</div><button class="secondary full" onclick="officeWalletAddCard()">+ Add another card</button>`}catch(e){box.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
window.officeWalletCharge=async function(paymentMethodId){if(!walletCtx)return;const amount=Number(el('walletChargeAmount')?.value||0);if(!amount||amount<=0)return alert('Enter an amount to charge.');if(!confirm(`Charge ${money(amount)} to this saved card?`))return;const box=el('walletBody');try{box.insertAdjacentHTML('afterbegin','<div id="walletChargeStatus" class="muted">Charging card securely…</div>');const d=await call({action:'charge',companyRef:walletCtx.companyRef,customerRef:walletCtx.customerRef,customerName:walletCtx.customerName,customerEmail:walletCtx.customerEmail,paymentMethodId,invoiceRef:walletCtx.invoice.id,invoiceNumber:walletCtx.invoice.number||'',amount});if(d.status!=='succeeded')throw new Error(`Payment status: ${d.status}`);logActivity(walletCtx.invoice.company,`Charged ${money(amount)} to saved card for ${walletCtx.customerName}`);if(typeof window.officePaymentHistory==='function')await window.officePaymentHistory(walletCtx.invoice.id);save();render();window.renderAccounting?.()}catch(e){el('walletChargeStatus')?.remove();alert(e.message||'Card could not be charged.')}};
window.officeWalletAddCard=async function(){if(!walletCtx)return;const box=el('walletBody');box.innerHTML=`<div class="item"><b>Save a customer card</b><div class="muted">The customer must authorize this business to save the card for future charges.</div></div><label class="check"><input id="walletConsent" type="checkbox"> Customer has authorized us to securely save this payment method for future charges.</label><div id="walletPaymentElement" style="margin:14px 0"></div><div id="walletSetupStatus" class="muted" style="font-size:12px;margin-bottom:8px"></div><button id="walletSaveCardBtn" class="primary full" onclick="officeWalletConfirmCard()">Save Card</button>`;try{const d=await call({action:'setup',companyRef:walletCtx.companyRef,customerRef:walletCtx.customerRef,customerName:walletCtx.customerName,customerEmail:walletCtx.customerEmail});const Stripe=await loadStripeJs();stripeClient=Stripe(d.publishableKey,{stripeAccount:d.stripeAccount});elements=stripeClient.elements({clientSecret:d.clientSecret,appearance:{theme:'stripe'}});elements.create('payment',{layout:'tabs'}).mount('#walletPaymentElement');walletCtx.setupClientSecret=d.clientSecret}catch(e){box.innerHTML=`<div class="empty">${esc(e.message||'Card form could not load.')}</div>`}}
window.officeWalletConfirmCard=async function(){if(!walletCtx||!stripeClient||!elements)return;if(!el('walletConsent')?.checked)return alert('Confirm the customer authorized this card to be saved.');const btn=el('walletSaveCardBtn'),status=el('walletSetupStatus');btn.disabled=true;btn.textContent='Saving…';try{const result=await stripeClient.confirmSetup({elements,clientSecret:walletCtx.setupClientSecret,redirect:'if_required',confirmParams:{return_url:location.href}});if(result.error)throw result.error;const pm=typeof result.setupIntent?.payment_method==='string'?result.setupIntent.payment_method:result.setupIntent?.payment_method?.id;if(!pm)throw new Error('Card was saved but could not be linked.');await call({action:'confirm_consent',companyRef:walletCtx.companyRef,customerRef:walletCtx.customerRef,customerName:walletCtx.customerName,customerEmail:walletCtx.customerEmail,paymentMethodId:pm,consent:true,consentNote:'Customer authorized secure card storage for future business charges.'});if(status)status.textContent='Card saved securely ✓';setTimeout(()=>officeWalletSavedCards(),600)}catch(e){if(status)status.textContent=e.message||'Card could not be saved.';btn.disabled=false;btn.textContent='Save Card'}};
window.officeCustomerWallet=function(customerId){const c=(db.customers||[]).find(x=>x.id===customerId);if(!c)return;const inv=(db.invoices||[]).filter(x=>x.company===c.company&&x.type==='Invoice'&&String(x.customer||'').trim().toLowerCase()===String(c.name||'').trim().toLowerCase()&&x.status!=='Paid').sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')))[0];if(inv)return officeTakePayment(inv.id);formTitle.textContent=`Wallet · ${c.name}`;formBody.innerHTML='<div class="empty">This customer has no open invoice. Saved cards can be used when an invoice is created.</div>';overlay.classList.add('open')};
function decorate(){for(const inv of relevant(db.invoices||[]).filter(x=>x.type==='Invoice')){const preview=[...document.querySelectorAll('#invoiceList button')].find(b=>(b.getAttribute('onclick')||'')===`previewInvoice('${inv.id}')`),actions=preview?.closest('.invoice-card')?.querySelector('.invoice-actions');if(actions&&!actions.querySelector(`[data-take-payment="${inv.id}"]`)){const b=document.createElement('button');b.className='primary';b.dataset.takePayment=inv.id;b.textContent='Take Payment';b.onclick=()=>officeTakePayment(inv.id);actions.appendChild(b)}}for(const c of relevant(db.customers||[])){const edit=[...document.querySelectorAll('#customerList button')].find(b=>(b.getAttribute('onclick')||'').includes(`'${c.id}'`)),actions=edit?.parentElement;if(actions&&!actions.querySelector(`[data-wallet="${c.id}"]`)){const b=document.createElement('button');b.className='secondary';b.dataset.wallet=c.id;b.textContent='Wallet';b.onclick=()=>officeCustomerWallet(c.id);actions.appendChild(b)}}}
setTimeout(decorate,2200);new MutationObserver(()=>setTimeout(decorate,20)).observe(document.body,{childList:true,subtree:true});
})();