(function(){
'use strict';
const el=id=>document.getElementById(id);let timer=null;
async function companyUuid(localId){const {data:{session}}=await supabaseClient.auth.getSession();if(!session?.user)return null;const {data}=await supabaseClient.from('companies').select('id').eq('owner_id',session.user.id).eq('external_ref',String(localId)).maybeSingle();return data?.id||null}
function age(ts){if(!ts)return'No recent ping';const m=Math.max(0,Math.floor((Date.now()-Date.parse(ts))/60000));return m<1?'Just now':m===1?'1 min ago':`${m} min ago`}
function statusText(s){return({working:'Working',en_route:'En route',at_job:'At job',paused:'Paused',ended:'Ended'})[s]||'Working'}
function mapsUrl(x){return `https://www.google.com/maps?q=${encodeURIComponent(x.latitude+','+x.longitude)}`}
async function load(){const host=el('dispatchBoard');if(!host)return;const local=typeof current==='function'?current():'all';let ids=[];if(local==='all'){for(const c of db.companies||[]){const id=await companyUuid(c.id);if(id)ids.push(id)}}else{const id=await companyUuid(local);if(id)ids=[id]}if(!ids.length){host.innerHTML='<div class="empty">No field companies are connected yet.</div>';return}const {data,error}=await supabaseClient.from('field_location_sessions').select('id,company_id,user_id,status,last_seen_at,latitude,longitude,accuracy_m,started_at,en_route_at,arrived_at').in('company_id',ids).eq('sharing',true).is('ended_at',null).order('last_seen_at',{ascending:false});if(error){host.innerHTML='<div class="empty">Dispatch could not load.</div>';return}const latest=[];for(const x of data||[])if(!latest.some(v=>v.user_id===x.user_id))latest.push(x);if(!latest.length){host.innerHTML='<div class="empty">No techs are sharing location right now.</div>';return}host.innerHTML=latest.map(x=>`<div class="dispatch-tech"><div class="row between"><div><b>Field Tech</b><div class="muted">${statusText(x.status)} · ${age(x.last_seen_at)}</div></div><span class="tag">${statusText(x.status)}</span></div><div class="dispatch-meta">${x.accuracy_m?`Location accuracy ±${Math.round(x.accuracy_m)}m`:''}</div>${x.latitude!=null&&x.longitude!=null?`<a class="secondary dispatch-map" href="${mapsUrl(x)}" target="_blank" rel="noopener">View Location</a>`:''}</div>`).join('')}
function install(){const page=el('jobs');if(!page)return;let card=el('dispatchCard');if(!card){card=document.createElement('div');card.id='dispatchCard';card.className='card dispatch-card';card.innerHTML='<div class="section-title"><div><div class="kicker">Dispatch</div><h2>Field Team</h2></div><button class="secondary" id="dispatchRefresh">Refresh</button></div><p class="muted">Only techs who have actively enabled work-location sharing appear here.</p><div id="dispatchBoard"><div class="empty">Loading field team…</div></div>';const loc=el('fieldLocationControl');if(loc)loc.insertAdjacentElement('afterend',card);else page.insertBefore(card,page.children[1]||null);el('dispatchRefresh')?.addEventListener('click',load)}load();clearInterval(timer);timer=setInterval(()=>{if(el('jobs')?.classList.contains('active'))load()},60000)}
window.renderDispatch=load;setTimeout(install,2400);document.querySelector('nav button[data-page="jobs"]')?.addEventListener('click',()=>setTimeout(load,200));
})();