(function(){
function el(id){return document.getElementById(id)}
function escField(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function field(){return window.OfficeOSField}
function member(){return field()?.memberForUser?.()||null}
function isFieldUser(){const m=member();return !!m&&['field','sales'].includes(m.role)}
function dateLabel(d){if(!d)return'Unscheduled';try{return new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}catch{return d}}
function statusButtons(job){const allowed=['On My Way','Arrived','In Progress','Waiting','Complete'];return `<div class="field-status-row">${allowed.map(s=>`<button class="${job.status===s?'primary':'secondary'}" onclick="officeFieldSetStatus('${job.id}','${s}')">${escField(s)}</button>`).join('')}</div>`}
function packetSections(job){const p=job.jobPacket||{},sections=Array.isArray(p.sections)?p.sections:[];if(!sections.length)return'<div class="field-empty">No job packet sections have been added yet.</div>';return sections.map(s=>`<div class="field-packet-section"><b>${escField(s.title||'Job detail')}</b><div>${escField(s.text||s.value||'')}</div></div>`).join('')}
function checklist(job){const a=job.jobPacket?.checklist||[];if(!a.length)return'<div class="field-empty">No checklist has been attached to this job.</div>';const done=a.filter(x=>x.done).length;return `<div class="field-progress"><div><b>${done}/${a.length}</b> complete</div><div class="field-progress-track"><i style="width:${a.length?Math.round(done/a.length*100):0}%"></i></div></div>${a.map(x=>`<label class="field-check ${x.done?'done':''}"><input type="checkbox" ${x.done?'checked':''} onchange="officeFieldToggleChecklist('${job.id}','${x.id}')"><span>${escField(x.title||'Checklist item')}${x.required===false?' <small>Optional</small>':''}</span></label>`).join('')}`}
function files(job){const a=job.jobFiles||[];const groups=['before','during','after','reference'];return groups.map(cat=>{const list=a.filter(x=>(x.category||'during')===cat);return `<div class="field-file-group"><div class="field-file-head"><b>${cat==='after'?'Completed / After':cat.charAt(0).toUpperCase()+cat.slice(1)}</b><span>${list.length}</span></div>${list.length?list.map(f=>`<div class="field-file"><div>📎</div><div><b>${escField(f.name)}</b><div class="muted">${escField(f.caption||'')}${f.memberName?' · '+escField(f.memberName):''}</div></div></div>`).join(''):'<div class="field-empty small">None yet.</div>'}</div>`}).join('')}
function notes(job){const a=job.fieldNotes||[];return `<div class="field-note-compose"><textarea id="fieldNote_${job.id}" placeholder="Add a field note…"></textarea><button class="secondary" onclick="officeFieldAddNote('${job.id}')">Add Note</button></div>${a.length?a.slice(0,8).map(n=>`<div class="field-note"><b>${escField(n.memberName||'Team member')}</b><div>${escField(n.text)}</div><time>${new Date(n.createdAt).toLocaleString()}</time></div>`).join(''):'<div class="field-empty">No field notes yet.</div>'}`}
function jobCard(job){const req=field().completionRequirements(job),packet=job.jobPacket||{};return `<article class="field-job-card" id="fieldJob_${job.id}"><div class="field-job-top"><div><div class="kicker">${escField(job.time||'Any time')} · ${escField(job.status||'Scheduled')}</div><h2>${escField(job.title||job.customer||'Job')}</h2><div class="muted">${escField(job.customer||'')}${job.address?' · '+escField(job.address):''}</div></div>${job.address?`<a class="field-map" target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(job.address)}">Directions</a>`:''}</div>${statusButtons(job)}<details open><summary>Job Packet${packet.templateName?' · '+escField(packet.templateName):''}</summary>${packetSections(job)}</details><details open><summary>Checklist</summary>${checklist(job)}</details><details><summary>Photos & Files</summary><div class="field-files-grid">${files(job)}</div><div class="field-upload-placeholder"><b>Secure uploads coming in this build</b><span>Before, during and completed-work photos will upload directly to protected OfficeOS storage and keep the employee/timestamp audit trail.</span></div></details><details><summary>Field Notes</summary>${notes(job)}</details>${req.requireChecklist||req.requireAfterPhoto?`<div class="field-requirements"><b>Completion requirements</b><span>${req.requireChecklist?`${req.missingChecklist} checklist item(s) remaining. `:''}${req.requireAfterPhoto&&!req.afterPhotos?'Completed-work photo required.':''}</span></div>`:''}</article>`}
function render(){const page=el('fieldMyDay');if(!page)return;const m=member();if(!m){page.innerHTML='<div class="field-empty">This workspace appears when a team member account is linked.</div>';return}const today=new Date().toISOString().slice(0,10),jobs=field().myDay(today);el('fieldMemberName').textContent=m.name||m.email||'Team member';el('fieldTodayDate').textContent=dateLabel(today);el('fieldJobCount').textContent=jobs.length;el('fieldJobList').innerHTML=jobs.length?jobs.map(jobCard).join(''):'<div class="field-empty big">No assigned jobs today.</div>'}
function install(){if(el('fieldMyDay'))return;const jobsPage=el('jobs');if(!jobsPage)return;const section=document.createElement('section');section.id='fieldMyDay';section.className='field-my-day';section.innerHTML=`<div class="field-hero"><div><div class="kicker">My Day</div><h1 id="fieldMemberName">Team Member</h1><div id="fieldTodayDate" class="muted"></div></div><div class="field-count"><strong id="fieldJobCount">0</strong><span>jobs today</span></div></div><div id="fieldJobList"></div>`;jobsPage.insertBefore(section,jobsPage.firstChild);if(isFieldUser()){[...jobsPage.children].forEach(ch=>{if(ch!==section)ch.classList.add('field-office-only')});jobsPage.classList.add('field-mode')}render()}
window.officeFieldSetStatus=function(jobId,status){try{field().setStatus(jobId,status);render()}catch(e){alert(e?.message||'Could not update job status.')}}
window.officeFieldToggleChecklist=function(jobId,itemId){try{field().toggleChecklist(jobId,itemId);render()}catch(e){alert(e?.message||'Could not update checklist.')}}
window.officeFieldAddNote=function(jobId){const input=el('fieldNote_'+jobId);try{field().addFieldNote(jobId,input?.value||'');if(input)input.value='';render()}catch(e){alert(e?.message||'Could not add note.')}}
window.officeRenderMyDay=render;
setTimeout(install,900);
const jt=document.createElement('script');jt.src='job-templates.js?v=1';jt.defer=true;document.body.appendChild(jt);
const ta=document.createElement('script');ta.src='team-admin.js?v=1';ta.defer=true;document.body.appendChild(ta);
})();