(function(){
const BUCKET='job-files',MAX_BYTES=15*1024*1024,ALLOWED=new Set(['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']);
function safeName(name){return String(name||'file').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(0,120)}
function jobFor(id){return(db.jobs||[]).find(j=>j.id===id)}
function companyFor(job){return(db.companies||[]).find(c=>c.id===job?.company)}
function member(){return window.OfficeOSField?.memberForUser?.()||null}
function canUpload(job){const f=window.OfficeOSField,m=member();if(!f)return false;if(m&&!f.assigned(job,m)&&!f.can('jobs.view_all',m))return false;return f.can('files.upload_assigned',m)||f.can('files.upload',m)}
async function upload(jobId,file,options={}){const job=jobFor(jobId);if(!job)throw new Error('Job not found.');if(!file)throw new Error('Choose a file.');if(!canUpload(job))throw new Error('You do not have permission to upload files to this job.');if(file.size>MAX_BYTES)throw new Error('File is too large. Maximum size is 15 MB.');if(file.type&&!ALLOWED.has(file.type))throw new Error('Use a photo or PDF file.');const company=companyFor(job);if(!company)throw new Error('Company not found.');const category=['before','during','after','reference'].includes(options.category)?options.category:'during';const path=`${company.id}/${job.id}/${Date.now()}-${safeName(file.name)}`;const {data,error}=await supabaseClient.storage.from(BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error){if(/bucket|not found/i.test(error.message||''))throw new Error('Secure job storage is not active in this environment yet.');throw error}return window.OfficeOSField.attachFileMeta(jobId,{storagePath:data?.path||path,name:file.name,type:file.type,category,caption:String(options.caption||'').trim(),customerVisible:options.customerVisible===true})}
async function signedUrl(storagePath,expires=900){if(!storagePath)return'';const {data,error}=await supabaseClient.storage.from(BUCKET).createSignedUrl(storagePath,expires);if(error)throw error;return data?.signedUrl||''}
async function remove(jobId,fileId){const job=jobFor(jobId),m=member(),f=window.OfficeOSField;if(!job)throw new Error('Job not found.');const rec=(job.jobFiles||[]).find(x=>x.id===fileId);if(!rec)throw new Error('File not found.');if(m&&rec.memberId!==m.id&&!f.can('files.upload',m))throw new Error('You do not have permission to remove this file.');if(rec.storagePath){const {error}=await supabaseClient.storage.from(BUCKET).remove([rec.storagePath]);if(error)throw error}job.jobFiles=job.jobFiles.filter(x=>x.id!==fileId);job.updatedAt=nowISO();db.fieldAudit=Array.isArray(db.fieldAudit)?db.fieldAudit:[];db.fieldAudit.unshift({id:uid(),company:job.company,jobId:job.id,memberId:m?.id||'',userId:currentUser?.id||'',action:'job_file_removed',detail:rec.name,createdAt:nowISO()});save();return true}
window.OfficeOSFieldStorage={BUCKET,MAX_BYTES,canUpload,upload,signedUrl,remove};
})();