(function(){
const oldOpenForm=window.openForm,oldRenderOffice=window.renderOffice;
function goPage(page){const b=document.querySelector(`nav button[data-page="${page}"]`);if(b)b.click()}
function wireStats(){const s=document.querySelectorAll('.stats .stat');if(s[0])s[0].onclick=()=>goPage('leads');if(s[1])s[1].onclick=()=>goPage('jobs');if(s[2])s[2].onclick=()=>goPage('calendar');if(s[3])s[3].onclick=()=>{goPage('more');setTimeout(()=>document.getElementById('invoiceList')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}}
function nextInvoiceNumber(){let max=0;for(const x of db.invoices||[]){const m=String(x.number||'').match(/(\d+)/);if(m)max=Math.max(max,Number(m[1]))}return `INV-${String(max+1).padStart(4,'0')}`}
function lineHTML(x={description:'',qty:1,rate:0}){return `<div class="invoice-row"><div><label>Description</label><input class="li-desc" value="${esc(x.description||'')}"></div><div><label>Qty</label><input class="li-qty" type="number" step="0.01" value="${Number(x.qty||1)}" oninput="invoiceRecalc()"></div><div><label>Rate</label><input class="li-rate" type="number" step="0.01" value="${Number(x.rate||0)}" oninput="invoiceRecalc()"></div><button type="button" class="danger remove-line" onclick="this.parentElement.remove();invoiceRecalc()">×</button></div>`}
window.addInvoiceLine=function(){document.getElementById('invoiceLines').insertAdjacentHTML('beforeend',lineHTML());invoiceRecalc()}
window.invoiceRecalc=function(){let sub=0;document.querySelectorAll('#invoiceLines .invoice-row').forEach(r=>sub+=Number(r.querySelector('.li-qty').value||0)*Number(r.querySelector('.li-rate').value||0));const tax=Number(document.getElementById('fTaxRate')?.value||0);const total=sub+(sub*tax/100);const a=document.getElementById('invoiceSubtotal'),b=document.getElementById('invoiceTax'),c=document.getElementById('invoiceGrand');if(a)a.textContent=money(sub);if(b)b.textContent=money(sub*tax/100);if(c)c.textContent=money(total)}
function professionalInvoiceForm(data){const today=new Date().toISOString().slice(0,10),due=data?.dueDate||today,lines=(data?.lines&&data.lines.length?data.lines:[{description:data?.description||'',qty:1,rate:Number(data?.amount||0)}]),statuses=['Draft','Sent','Open','Overdue',...(data?.status==='Paid'?['Paid']:[])];formTitle.textContent=data?'Edit Invoice':'Create Invoice';formBody.innerHTML=`<div class="invoice-builder"><div class="row"><div style="flex:1"><label>Invoice #</label><input id="fInvNumber" value="${esc(data?.number||nextInvoiceNumber())}"></div><div style="flex:1"><label>Status</label><select id="fInvStatus">${statuses.map(s=>`<option ${data?.status===s?'selected':''}>${s}</option>`).join('')}</select>${data?.status==='Paid'?'<div class="muted" style="font-size:12px;margin-top:6px">Paid status is controlled by recorded payments.</div>':''}</div></div><label>Company</label><select id="fCompany">${companyOptions(data?.company||(current()==='all'?db.companies[0]?.id:current()))}</select><label>Customer Name</label><input id="fCustomer" value="${esc(data?.customer||'')}"><label>Customer Email</label><input id="fInvEmail" type="email" value="${esc(data?.email||'')}"><div class="row"><div style="flex:1"><label>Issue Date</label><input id="fIssueDate" type="date" value="${data?.issueDate||today}"></div><div style="flex:1"><label>Due Date</label><input id="fDueDate" type="date" value="${due}"></div></div><label>Line Items</label><div id="invoiceLines">${lines.map(lineHTML).join('')}</div><button type="button" class="secondary" onclick="addInvoiceLine()">+ Add Line Item</button><label>Tax %</label><input id="fTaxRate" type="number" step="0.01" value="${Number(data?.taxRate||0)}" oninput="invoiceRecalc()"><div class="invoice-summary"><div class="sumrow"><span>Subtotal</span><b id="invoiceSubtotal">$0</b></div><div class="sumrow"><span>Tax</span><b id="invoiceTax">$0</b></div><div class="sumrow total"><span>Total</span><span id="invoiceGrand">$0</span></div></div><label>Terms / Notes</label><textarea id="fInvNotes">${esc(data?.notes||'Thank you for your business!')}</textarea><button class="primary full" onclick="saveProfessionalInvoice('${data?.id||''}')">Save Invoice</button></div>`;setTimeout(invoiceRecalc,0)}
window.openForm=function(type,data=null){if(type==='invoice'){overlay.classList.add('open');professionalInvoiceForm(data);return}return oldOpenForm(type,data)}
window.saveProfessionalInvoice=function(i){if(!fCustomer.value.trim())return alert('Enter a customer name.');const lines=[...document.querySelectorAll('#invoiceLines .invoice-row')].map(r=>({description:r.querySelector('.li-desc').value.trim(),qty:Number(r.querySelector('.li-qty').value||0),rate:Number(r.querySelector('.li-rate').value||0)})).filter(x=>x.description||x.rate);const sub=lines.reduce((a,x)=>a+x.qty*x.rate,0),taxRate=Number(fTaxRate.value||0),amount=sub+(sub*taxRate/100),old=db.invoices.find(v=>v.id===i),status=old?.status==='Paid'?'Paid':fInvStatus.value;const x=stamp({id:i||uid(),company:fCompany.value,customer:fCustomer.value.trim(),email:fInvEmail.value.trim(),type:'Invoice',number:fInvNumber.value.trim()||nextInvoiceNumber(),issueDate:fIssueDate.value,dueDate:fDueDate.value,status,lines,taxRate,amount,notes:fInvNotes.value.trim(),paymentUrl:old?.paymentUrl||'',paidAmount:old?.paidAmount||0,balanceDue:old?.balanceDue,paidAt:old?.paidAt||'',createdAt:old?.createdAt});if(i)db.invoices=db.invoices.map(v=>v.id===i?x:v);else db.invoices.push(x);logActivity(x.company,`${i?'Updated':'Created'} invoice ${x.number} for ${x.customer}`);closeForm();save()}
function invText(x){const lines=(x.lines||[]).map(l=>`${l.description} — ${l.qty} × ${money(l.rate)} = ${money(l.qty*l.rate)}`).join('\n');return `Invoice ${x.number||''}\nFrom: ${companyName(x.company)}\nTo: ${x.customer}\nIssue date: ${x.issueDate||''}\nDue date: ${x.dueDate||''}\n\n${lines}\n\nTotal: ${money(x.amount)}\n${x.notes||''}${x.paymentUrl?`\n\nPay securely: ${x.paymentUrl}`:''}`}
window.emailInvoice=function(i){const x=db.invoices.find(v=>v.id===i);if(!x)return;if(!x.email)return alert('Add the customer email to this invoice first.');const subject=encodeURIComponent(`Invoice ${x.number||''} from ${companyName(x.company)}`),body=encodeURIComponent(invText(x));window.location.href=`mailto:${encodeURIComponent(x.email)}?subject=${subject}&body=${body}`;if(x.status==='Draft'){x.status='Sent';x.updatedAt=nowISO();save()}}
window.copyInvoice=function(i){const x=db.invoices.find(v=>v.id===i);if(!x)return;navigator.clipboard?.writeText(invText(x)).then(()=>alert('Invoice details copied.'))}
window.previewInvoice=function(i){const x=db.invoices.find(v=>v.id===i);if(!x)return;formTitle.textContent=x.number||'Invoice';const subtotal=(x.lines||[]).reduce((a,l)=>a+Number(l.qty||0)*Number(l.rate||0),0);formBody.innerHTML=`<div class="invoice-preview"><h2>${esc(companyName(x.company))}</h2><div class="muted">Invoice ${esc(x.number||'')}</div><div class="row between" style="margin-top:18px"><div><b>Bill to</b><div>${esc(x.customer)}</div><div class="muted">${esc(x.email||'')}</div></div><div><b>Due</b><div>${esc(x.dueDate||'')}</div></div></div><table><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${(x.lines||[]).map(l=>`<tr><td>${esc(l.description)}</td><td>${l.qty}</td><td>${money(l.rate)}</td><td>${money(l.qty*l.rate)}</td></tr>`).join('')}</tbody></table><div class="invoice-summary"><div class="sumrow"><span>Subtotal</span><b>${money(subtotal)}</b></div><div class="sumrow"><span>Tax</span><b>${money(Number(x.amount||0)-subtotal)}</b></div><div class="sumrow total"><span>Total</span><span>${money(x.amount)}</span></div></div>${x.paymentUrl?`<a class="primary full quicklink" style="text-align:center;color:#fff" href="${esc(x.paymentUrl)}" target="_blank">Pay Invoice</a>`:''}<p class="muted">${esc(x.notes||'')}</p></div>`;overlay.classList.add('open')}
function renderProInvoices(){const box=document.getElementById('invoiceList');if(!box)return;const a=relevant(db.invoices).filter(x=>x.type==='Invoice'||!x.type);box.innerHTML=a.length?a.slice().reverse().map(x=>`<div class="invoice-card"><div class="inv-head"><div><b>${esc(x.number||'Invoice')}</b><div class="muted">${esc(x.customer)}${x.dueDate?` • Due ${esc(x.dueDate)}`:''}</div></div><div style="text-align:right"><b>${money(x.amount)}</b><br><span class="invoice-status ${esc(x.status||'Draft')}">${esc(x.status||'Draft')}</span></div></div><div class="invoice-actions"><button class="secondary" onclick="previewInvoice('${x.id}')">Preview</button><button class="secondary" onclick="editItem('invoice','${x.id}')">Edit</button><button class="blue" onclick="emailInvoice('${x.id}')">Send</button><button class="secondary" onclick="copyInvoice('${x.id}')">Copy</button>${x.paymentUrl?`<a class="quicklink" target="_blank" href="${esc(x.paymentUrl)}">Pay Link</a>`:''}${x.status!=='Paid'?`<button class="success" onclick="officeTakePayment('${x.id}')">Take Payment</button>`:''}</div>${!x.paymentUrl?`<div class="invoice-pay-note">Online payment links will appear here after the business connects its own Stripe payments account.</div>`:''}</div>`).join(''):'<div class="empty">No invoices yet.</div>'}
window.renderOffice=function(){oldRenderOffice();renderProInvoices()}
setTimeout(()=>{wireStats();renderProInvoices()},250);
})();