(function(){
const BUCKET='job-photos';
let draft={jobId:null,existing:[],files:[],removed:[]};
const el=id=>document.getElementById(id);
function safeExt(file){const raw=(file.name||'photo.jpg').split('.').pop().toLowerCase();return ['jpg','jpeg','png','webp','heic','heif'].includes(raw)?raw:'jpg'}
function mimeFor(file){const ext=safeExt(file),map={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif'};return map[ext]||(/^image\//i.test(file?.type||'')?file.type:'image/jpeg')}
function resetDraft(data){draft={jobId:data?.id||uid(),existing:Array.isArray(data?.photos)?data.photos.map(x=>({...x})):[],files:[],removed:[]}}
function photoCount(job){return Array.isArray(job?.photos)?job.photos.length:0}
function companyFor(id){return(db.companies||[]).find(x=>x.id===id)}
function matchesJobType(job,rule){const hay=`${job?.jobType||''} ${job?.title||''}`.toLowerCase(),needle=String(rule||'').toLowerCase();return needle&&hay.includes(needle)}
function requiresCompletionPhoto(companyId,job={}){const p=companyFor(companyId)?.playbook||{};if(p.requireCompletionPhoto)return true;return(Array.isArray(p.completionPhotoJobTypes)?p.completionPhotoJobTypes:[]).some(type=>matchesJobType(job,type))}
function requirementText(companyId,job={}){if(!requiresCompletionPhoto(companyId,job))return'';const p=companyFor(companyId)?.playbook||{};if(p.requireCompletionPhoto)return'Photo required before this job can be completed.';const match=(p.completionPhotoJobTypes||[]).find(type=>matchesJobType(job,type));return match?`${match} jobs require a completion photo.`:'Photo required before this job can be completed.'}
function currentDraftJob(data={}){return{jobType:el('fJobType')?.value||data?.jobType||'',title:el('fTitle')?.value||data?.title||''}}
function injectPhotoUI(data){const body=el('formBody');if(!body||!el('fCustomer'))return;resetDraft(data);const saveBtn=[...body.querySelectorAll('button')].find(b=>/save job/i.test(b.textContent||''));if(!saveBtn)return;const title=el('fTitle');if(title&&!el('fJobType')){const label=document.createElement('label');label.textContent='Job Type';const select=document.createElement('select');select.id='fJobType';const standard=['Installation','Repair','Estimate','Delivery','Service','Other'],saved=data?.jobType||'';select.innerHTML=['',...new Set([...standard,saved].filter(Boolean))].map(v=>`<option value="${esc(v)}" ${v===saved?'selected':''}>${v||'Choose job type'}</option>`).join('');title.insertAdjacentElement('afterend',select);title.insertAdjacentElement('afterend',label)}const companyId=el('fCompany')?.value||data?.company||'';const wrap=document.createElement('div');wrap.className='job-photo-block';wrap.innerHTML=`<div class="row between"><div><label style="margin:0">Job Photos</label><div class="muted">Add photos now, on site, or when the work is finished.</div><div id="jobPhotoRequirement" class="job-photo-required" style="display:none"></div></div><span id="jobPhotoCount" class="tag">0 photos</span></div><div class="job-photo-actions"><button type="button" class="secondary" onclick="officeTakeJobPhoto()">📷 Take Photo</button><button type="button" class="secondary" onclick="officeChooseJobPhotos()">＋ Choose Photos</button></div><input id="jobCameraInput" type="file" accept="image/*" capture="environment" hidden><input id="jobLibraryInput" type="file" accept="image/*" multiple hidden><div id="jobPhotoPreview" class="job-photo-grid"></div>`;saveBtn.insertAdjacentElement('beforebegin',wrap);el('jobCameraInput').onchange=e=>queueFiles(e.target.files);el('jobLibraryInput').onchange=e=>queueFiles(e.target.files);const update=()=>{const text=requirementText(el('fCompany')?.value||companyId,currentDraftJob(data)),note=el('jobPhotoRequirement');if(note){note.textContent=text;note.style.display=text?'block':'none'}};el('fCompany')?.addEventListener('change',update);el('fJobType')?.addEventListener('change',update);el('fTitle')?.addEventListener('input',update);update();renderDraftPhotos()}
window.officeTakeJobPhoto=()=>{const x=el('jobCameraInput');if(x){x.value='';x.click()}};window.officeChooseJobPhotos=()=>{const x=el('jobLibraryInput');if(x){x.value='';x.click()}};
function queueFiles(list){for(const f of Array.from(list||[])){const type=mimeFor(f);if(!type.startsWith('image/'))continue;if(f.size>10*1024*1024){alert(`${f.name||'That photo'} is larger than 10 MB.`);continue}draft.files.push({id:uid(),file:f,url:URL.createObjectURL(f)})}renderDraftPhotos()}
window.officeRemoveDraftPhoto=function(kind,id){if(kind==='new'){const x=draft.files.find(v=>v.id===id);if(x?.url)URL.revokeObjectURL(x.url);draft.files=draft.files.filter(v=>v.id!==id)}else{const x=draft.existing.find(v=>v.path===id);if(x){draft.removed.push(x);draft.existing=draft.existing.filter(v=>v.path!==id)}}renderDraftPhotos()};
async function signed(path){const {data,error}=await supabaseClient.storage.from(BUCKET).createSignedUrl(path,3600);return error?'':(data?.signedUrl||'')}
async function renderDraftPhotos(){const box=el('jobPhotoPreview'),badge=el('jobPhotoCount');if(!box)return;const total=draft.existing.length+draft.files.length;if(badge)badge.textContent=`${total} photo${total===1?'':'s'}`;box.innerHTML='';for(const p of draft.existing){const cell=document.createElement('div');cell.className='job-photo-thumb loading';cell.innerHTML=`<div class="job-photo-placeholder">Photo</div><button type="button" aria-label="Remove photo">×</button>`;cell.querySelector('button').onclick=()=>officeRemoveDraftPhoto('existing',p.path);box.appendChild(cell);signed(p.path).then(url=>{if(!url||!cell.isConnected)return;cell.classList.remove('loading');cell.insertAdjacentHTML('afterbegin',`<img src="${url}" alt="Job photo">`);cell.querySelector('.job-photo-placeholder')?.remove()})}for(const p of draft.files){const cell=document.createElement('div');cell.className='job-photo-thumb';cell.innerHTML=`<img src="${p.url}" alt="New job photo"><button type="button" aria-label="Remove photo">×</button>`;cell.querySelector('button').onclick=()=>officeRemoveDraftPhoto('new',p.id);box.appendChild(cell)}}
async function uploadQueued(jobId){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)throw new Error('Please sign in again before uploading photos.');const uploaded=[];for(const item of draft.files){const f=item.file,path=`${user.id}/${jobId}/${Date.now()}-${uid()}.${safeExt(f)}`,contentType=mimeFor(f);const {error}=await supabaseClient.storage.from(BUCKET).upload(path,f,{contentType,upsert:false});if(error)throw new Error(`Could not upload ${f.name||'a photo'}: ${error.message}`);uploaded.push({path,name:f.name||'Job photo',type:contentType,size:f.size,createdAt:nowISO()})}return uploaded}
async function deleteRemoved(){for(const p of draft.removed){if(p?.path)await supabaseClient.storage.from(BUCKET).remove([p.path])}}
const originalOpenForm=window.openForm;window.openForm=function(type,data=null){const r=originalOpenForm(type,data);if(type==='job')setTimeout(()=>injectPhotoUI(data),0);return r};
window.saveJob=async function(i){if(!el('fCustomer')?.value.trim())return alert('Enter the customer.');const btn=[...document.querySelectorAll('#formBody button')].find(b=>/save job/i.test(b.textContent||''));if(btn){btn.disabled=true;btn.textContent='Saving Job…'}try{const old=db.jobs.find(v=>v.id===i),jobId=i||draft.jobId||uid(),newPhotos=await uploadQueued(jobId);await deleteRemoved();const companyId=el('fCompany').value,status=el('fStatus').value,photos=[...draft.existing,...newPhotos],jobType=el('fJobType')?.value||old?.jobType||'',title=el('fTitle').value.trim()||'Job',candidate={jobType,title};if(status==='Complete'&&requiresCompletionPhoto(companyId,candidate)&&photos.length===0)throw new Error(requirementText(companyId,candidate)+' Add at least one photo before marking it Complete.');const x=stamp({id:jobId,company:companyId,jobType,title,customer:el('fCustomer').value.trim(),status,date:el('fDate').value,time:el('fTime').value,address:el('fAddress').value.trim(),amount:Number(el('fAmount').value||0),notes:el('fNotes').value.trim(),photos,createdAt:old?.createdAt});if(i)db.jobs=db.jobs.map(v=>v.id===i?x:v);else db.jobs.push(x);syncJobEvent(x);logActivity(x.company,`${i?'Updated':'Added'} job for ${x.customer}${x.photos.length?` · ${x.photos.length} photo${x.photos.length===1?'':'s'}`:''}`);closeForm();save()}catch(e){console.error('[OfficeOS job photo upload]',e);alert(e?.message||'The job could not be saved.')}finally{if(btn){btn.disabled=false;btn.textContent='Save Job'}}};
const baseCompleteJob=window.completeJob;window.completeJob=function(i){const job=(db.jobs||[]).find(v=>v.id===i);if(!job)return;if(requiresCompletionPhoto(job.company,job)&&photoCount(job)===0){alert(requirementText(job.company,job)+' Add at least one photo before marking this job complete.');openForm('job',job);return}return baseCompleteJob(i)};
const originalRenderJobs=window.renderJobs;window.renderJobs=function(){const r=originalRenderJobs.apply(this,arguments);for(const job of relevant(db.jobs||[])){const count=photoCount(job),edit=[...document.querySelectorAll('#jobList button')].find(b=>b.getAttribute('onclick')===`editItem('job','${job.id}')`);if(!edit)continue;if(count){const marker=document.createElement('button');marker.className='secondary job-photo-count-btn';marker.type='button';marker.textContent=`📷 ${count}`;marker.onclick=()=>editItem('job',job.id);edit.insertAdjacentElement('afterend',marker)}else if(requiresCompletionPhoto(job.company,job)&&job.status!=='Complete'){const req=document.createElement('span');req.className='tag job-photo-required-tag';req.textContent='📷 Required';edit.insertAdjacentElement('afterend',req)}}return r};
})();