(function(){
'use strict';
const el=id=>document.getElementById(id);
function ensure(){db.expenses=Array.isArray(db.expenses)?db.expenses:[]}
function cid(){return typeof current==='function'?current():'all'}
function rows(){ensure();return cid()==='all'?db.expenses:db.expenses.filter(x=>x.company===cid())}
function jobs(companyId){return(db.jobs||[]).filter(j=>j.company===companyId)}
function jobName(id){const j=(db.jobs||[]).find(x=>x.id===id);return j?`${j.customer||'Customer'} — ${j.title||'Job'}`:'General overhead'}
function form(x=null){ensure();const companyId=x?.company||(cid()==='all'?(db.companies?.[0]?.id||''):cid()),today=new Date().toISOString().slice(0,10);formTitle.textContent=x?'Edit Expense':'Add Expense';formBody.innerHTML=`<label>Company</label><select id="costCompany">${(db.companies||[]).map(c=>`<option value="${c.id}" ${c.id===companyId?'selected':''}>${esc(c.name)}</option>`).join('')}</select><label>Vendor / Description</label><input id="costVendor" value="${esc(x?.vendor||'')}" placeholder="Stone supplier, fuel, dump fee..."><div class="row"><div style="flex:1"><label>Amount</label><input id="costAmount" type="number" min="0" step="0.01" value="${Number(x?.amount||0)}"></div><div style="flex:1"><label>Date</label><input id="costDate" type="date" value="${x?.date||today}"></div></div><label>Category</label><select id="costCategory">${['Materials','Labor','Subcontractor','Fuel / Travel','Equipment','Permits / Fees','Other'].map(v=>`<option ${x?.category===v?'selected':''}>${v}</option>`).join('')}</select><label>Job</label><select id="costJob"><option value="">General overhead</option>${jobs(companyId).map(j=>`<option value="${j.id}" ${x?.jobId===j.id?'selected':''}>${esc(j.customer||'Customer')} — ${esc(j.title||'Job')}</option>`).join('')}</select><label>Notes</label><textarea id="costNotes">${esc(x?.notes||'')}</textarea><button class="primary full" onclick="officeSaveExpense('${x?.id||''}')">Save Expense</button>`;el('costCompany').addEventListener('change',()=>{const s=el('costJob'),selected=s.value;s.innerHTML='<option value="">General overhead</option>'+jobs(el('costCompany').value).map(j=>`<option value="${j.id}">${esc(j.customer||'Customer')} — ${esc(j.title||'Job')}</option>`).join('');if([...s.options].some(o=>o.value===selected))s.value=selected});overlay.classList.add('open')}
window.officeAddExpense=()=>form();window.officeEditExpense=id=>form(db.expenses.find(x=>x.id===id));
window.officeSaveExpense=function(id=''){ensure();const vendor=el('costVendor').value.trim(),amount=Number(el('costAmount').value||0);if(!vendor)return alert('Enter a vendor or description.');if(!Number.isFinite(amount)||amount<0)return alert('Enter a valid amount.');const old=db.expenses.find(x=>x.id===id),x={id:id||uid(),company:el('costCompany').value,vendor,amount,date:el('costDate').value,category:el('costCategory').value,jobId:el('costJob').value,notes:el('costNotes').value.trim(),createdAt:old?.createdAt||nowISO(),updatedAt:nowISO()};if(id)db.expenses=db.expenses.map(v=>v.id===id?x:v);else db.expenses.unshift(x);logActivity(x.company,`${id?'Updated':'Added'} expense ${x.vendor} · ${money(x.amount)}${x.jobId?' · '+jobName(x.jobId):''}`);closeForm();save();render()};
window.officeDeleteExpense=function(id){const x=db.expenses.find(v=>v.id===id);if(!x)return;if(!confirm(`Delete ${x.vendor} expense?`))return;db.expenses=db.expenses.filter(v=>v.id!==id);logActivity(x.company,`Deleted expense ${x.vendor}`);save();render()};
function profitRows(){const visibleJobs=cid()==='all'?(db.jobs||[]):jobs(cid());return visibleJobs.filter(j=>Number(j.amount||0)>0||rows().some(e=>e.jobId===j.id)).map(j=>{const costs=rows().filter(e=>e.jobId===j.id).reduce((s,e)=>s+Number(e.amount||0),0),revenue=Number(j.amount||0);return{j,costs,revenue,profit:revenue-costs}}).sort((a,b)=>b.profit-a.profit)}
function render(){ensure();const host=el('accountingHome');if(!host)return;let section=el('jobCostingCenter');if(!section){section=document.createElement('div');section.id='jobCostingCenter';host.appendChild(section)}const ex=rows(),jobCosts=ex.filter(x=>x.jobId).reduce((s,x)=>s+Number(x.amount||0),0),overhead=ex.filter(x=>!x.jobId).reduce((s,x)=>s+Number(x.amount||0),0),profits=profitRows();section.innerHTML=`<div class="card"><div class="section-title"><div><div class="kicker">Money Out</div><h2>Expenses</h2></div><button class="primary" onclick="officeAddExpense()">+ Expense</button></div><div class="stats"><div class="stat"><strong>${money(jobCosts)}</strong><span>Job Costs</span></div><div class="stat"><strong>${money(overhead)}</strong><span>Overhead</span></div><div class="stat"><strong>${money(jobCosts+overhead)}</strong><span>Total Expenses</span></div></div>${ex.length?ex.slice(0,12).map(x=>`<div class="item"><div class="row between"><div><b>${esc(x.vendor)}</b><div class="muted">${esc(x.category)} · ${x.jobId?esc(jobName(x.jobId)):'General overhead'} · ${dateText(x.date)}</div></div><b>${money(x.amount)}</b></div><div class="row wrap" style="margin-top:8px"><button class="secondary" onclick="officeEditExpense('${x.id}')">Edit</button><button class="danger" onclick="officeDeleteExpense('${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No expenses recorded yet.</div>'}</div><div class="card"><div class="kicker">Job Costing</div><h2>Revenue vs. Cost</h2><p class="muted">Attach expenses to jobs to see estimated gross profit before overhead and taxes.</p>${profits.length?profits.slice(0,12).map(({j,revenue,costs,profit})=>`<div class="item"><div class="row between"><div><b>${esc(j.customer||j.title||'Job')}</b><div class="muted">${esc(j.title||'Job')} · Revenue ${money(revenue)} · Costs ${money(costs)}</div></div><b>${money(profit)}</b></div><span class="tag">${revenue?Math.round((profit/revenue)*100):0}% gross margin</span></div>`).join(''):'<div class="empty">Add job amounts and job-linked expenses to see profitability.</div>'}</div>`}
const old=window.renderAccounting;window.renderAccounting=function(){const r=old?.apply(this,arguments);setTimeout(render,0);return r};document.querySelector('nav button[data-page="accounting"]')?.addEventListener('click',()=>setTimeout(render,100));setTimeout(render,1600);
})();