(function(){
const BUCKET='job-photos';
let draft={jobId:null,existing:[],files:[],removed:[]};
const el=id=>document.getElementById(id);
function safeExt(file){const raw=(file.name||'photo.jpg').split('.').pop().toLowerCase();return ['jpg','jpeg','png','webp','heic','heif'].includes(raw)?raw:'jpg'}
function resetDraft(data){draft={jobId:data?.id||uid(),existing:Array.isArray(data?.photos)?data.photos.map(x=>({...x})):[],files:[],removed:[]}}
function photoCount(job){return Array.isArray(job?.photos)?job.photos.length:0}
function injectPhotoUI(data){const body=el('formBody');if(!body||!el('fCustomer'))return;resetDraft(data);const saveBtn=[...body.querySelectorAll('button')].find(b=>/save job/i.test(b.textContent||''));if(!saveBtn)return;const wrap=document.createElement('div');wrap.className='job-photo-block';wrap.innerHTML=`<div class="row between"><div><label style="margin:0">Job Photos</label><div class="muted">Take photos on site or add them from your library.</div></div><span id="jobPhotoCount" class="tag">0 photos</span></div><div class="job-photo-actions"><button type="button" class="secondary" onclick="officeTakeJobPhoto()">📷 Take Photo</button><button type="button" class="secondary" onclick="officeChooseJobPhotos()">＋ Choose Photos</button></div><input id="jobCameraInput" type="file" accept="image/*" capture="environment" hidden><input id="jobLibraryInput" type="file" accept="image/*" multiple hidden><div id="jobPhotoPreview" class="job-photo-grid"></div>`;saveBtn.insertAdjacentElement('beforebegin',wrap);el('jobCameraInput').onchange=e=>queueFiles(e.target.files);el('jobLibraryInput').onchange=e=>queueFiles(e.target.files);renderDraftPhotos()}
window.officeTakeJobPhoto=()=>{const x=el('jobCameraInput');if(x){x.value='';x.click()}};
window.officeChooseJobPhotos=()=>{const x=el('jobLibraryInput');if(x){x.value='';x.click()}};
function queueFiles(list){for(const f of Array.from(list||[])){if(!f.type.startsWith('image/'))continue;if(f.size>10*1024*1024){alert(`${f.name||'That photo'} is larger than 10 MB.`);continue}draft.files.push({id:uid(),file:f,url:URL.createObjectURL(f)})}renderDraftPhotos()}
window.officeRemoveDraftPhoto=function(kind,id){if(kind==='new'){const x=draft.files.find(v=>v.id===id);if(x?.url)URL.revokeObjectURL(x.url);draft.files=draft.files.filter(v=>v.id!==id)}else{const x=draft.existing.find(v=>v.path===id);if(x){draft.removed.push(x);draft.existing=draft.existing.filter(v=>v.path!==id)}}renderDraftPhotos()};
async function signed(path){const {data,error}=await supabaseClient.storage.from(BUCKET).createSignedUrl(path,3600);return error?'':(data?.signedUrl||'')}
async function renderDraftPhotos(){const box=el('jobPhotoPreview'),badge=el('jobPhotoCount');if(!box)return;const total=draft.existing.length+draft.files.length;if(badge)badge.textContent=`${total} photo${total===1?'':'s'}`;box.innerHTML='';for(const p of draft.existing){const cell=document.createElement('div');cell.className='job-photo-thumb loading';cell.innerHTML=`<div class="job-photo-placeholder">Photo</div><button type="button" aria-label="Remove photo">×</button>`;cell.querySelector('button').onclick=()=>officeRemoveDraftPhoto('existing',p.path);box.appendChild(cell);signed(p.path).then(url=>{if(!url||!cell.isConnected)return;cell.classList.remove('loading');cell.insertAdjacentHTML('afterbegin',`<img src="${url}" alt="Job photo">`);cell.querySelector('.job-photo-placeholder')?.remove()})}for(const p of draft.files){const cell=document.createElement('div');cell.className='job-photo-thumb';cell.innerHTML=`<img src="${p.url}" alt="New job photo"><button type="button" aria-label="Remove photo">×</button>`;cell.querySelector('button').onclick=()=>officeRemoveDraftPhoto('new',p.id);box.appendChild(cell)}}
async function uploadQueued(jobId){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)throw new Error('Please sign in again before uploading photos.');const uploaded=[];for(const item of draft.files){const f=item.file,path=`${user.id}/${jobId}/${Date.now()}-${uid()}.${safeExt(f)}`;const {error}=await supabaseClient.storage.from(BUCKET).upload(path,f,{contentType:f.type||'image/jpeg',upsert:false});if(error)throw new Error(`Could not upload ${f.name||'a photo'}: ${error.message}`);uploaded.push({path,name:f.name||'Job photo',type:f.type||'image/jpeg',size:f.size,createdAt:nowISO()})}return uploaded}
async function deleteRemoved(){for(const p of draft.removed){if(!p?.path)continue;await supabaseClient.storage.from(BUCKET).remove([p.path])}}
const originalOpenForm=window.openForm;
window.openForm=function(type,data=null){const r=originalOpenForm(type,data);if(type==='job')setTimeout(()=>injectPhotoUI(data),0);return r};
window.saveJob=async function(i){if(!el('fCustomer')?.value.trim())return alert('Enter the customer.');const btn=[...document.querySelectorAll('#formBody button')].find(b=>/save job/i.test(b.textContent||''));if(btn){btn.disabled=true;btn.textContent='Saving Job…'}try{const old=db.jobs.find(v=>v.id===i),jobId=i||draft.jobId||uid(),newPhotos=await uploadQueued(jobId);await deleteRemoved();const x=stamp({id:jobId,company:el('fCompany').value,title:el('fTitle').value.trim()||'Job',customer:el('fCustomer').value.trim(),status:el('fStatus').value,date:el('fDate').value,time:el('fTime').value,address:el('fAddress').value.trim(),amount:Number(el('fAmount').value||0),notes:el('fNotes').value.trim(),photos:[...draft.existing,...newPhotos],createdAt:old?.createdAt});if(i)db.jobs=db.jobs.map(v=>v.id===i?x:v);else db.jobs.push(x);syncJobEvent(x);logActivity(x.company,`${i?'Updated':'Added'} job for ${x.customer}${x.photos.length?` · ${x.photos.length} photo${x.photos.length===1?'':'s'}`:''}`);closeForm();save()}catch(e){alert(e?.message||'The job could not be saved.')}finally{if(btn){btn.disabled=false;btn.textContent='Save Job'}}};
const originalRenderJobs=window.renderJobs;
window.renderJobs=function(){const r=originalRenderJobs.apply(this,arguments);for(const job of relevant(db.jobs||[])){const count=photoCount(job);if(!count)continue;const edit=[...document.querySelectorAll('#jobList button')].find(b=>b.getAttribute('onclick')===`editItem('job','${job.id}')`);if(!edit)continue;const marker=document.createElement('button');marker.className='secondary job-photo-count-btn';marker.type='button';marker.textContent=`📷 ${count}`;marker.onclick=()=>editItem('job',job.id);edit.insertAdjacentElement('afterend',marker)}return r};
})();