(function(){
const ENDPOINT='https://bowrytgqbunodtmzvabp.supabase.co/functions/v1/send-lead-welcome';
const FEATURE_START='2026-08-17T13:00:00Z';
function companyFor(id){return (db.companies||[]).find(c=>c.id===id)}
function currentCompany(){return typeof company==='function'?company():null}
function defaultSubject(c){return `Thanks for contacting ${c?.name||'us'}`}
function defaultMessage(){return `Thanks for reaching out to {company}! We received your request about {service} and someone from our team will be in touch shortly to discuss your project.\n\nWe look forward to working with you!`}
function emailConfig(c){const p=c?.playbook||{};return{enabled:p.initialEmailEnabled!==false,subject:p.initialEmailSubject||defaultSubject(c),message:p.initialEmailMessage||defaultMessage()}}
function isNewEnough(lead){const t=Date.parse(lead?.createdAt||'');return Number.isFinite(t)&&t>=Date.parse(FEATURE_START)}
function eligible(lead){return !!(lead?.id&&lead?.email&&!lead.initialEmailSentAt&&!lead.initialEmailSending&&!lead.initialEmailSuppressed&&isNewEnough(lead)&&(!lead.status||lead.status==='New'))}
async function flush(){if(typeof cloudSave!=='function'||!currentUser)return;const started=Date.now();while(typeof saving!=='undefined'&&saving&&Date.now()-started<8000)await new Promise(r=>setTimeout(r,100));await cloudSave()}
async function sendWelcome(lead,{force=false}={}){if(!lead?.id||!lead?.email||lead.initialEmailSentAt||lead.initialEmailSending)return{ok:false,skipped:true};if(!force&&!eligible(lead))return{ok:false,skipped:true};const c=companyFor(lead.company);if(!c)return{ok:false,skipped:true};const cfg=emailConfig(c);if(!cfg.enabled&&!force)return{ok:false,skipped:true};lead.initialEmailSending=true;delete lead.initialEmailError;try{await flush();const{data:{session}}=await supabaseClient.auth.getSession();if(!session?.access_token)throw new Error('Sign in required');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify({leadId:lead.id,force})});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.error||'Email failed');if(data.pending)return{ok:true,pending:true};lead.initialEmailSentAt=data.sentAt||nowISO();lead.initialEmailId=data.id||'';lead.updatedAt=nowISO();delete lead.initialEmailError;logActivity(lead.company,data.duplicate?`Initial response already sent to ${lead.name}`:`Initial response emailed to ${lead.name}`);save();await flush();return{ok:true,duplicate:!!data.duplicate}}catch(e){lead.initialEmailError=String(e?.message||'Email failed');lead.updatedAt=nowISO();logActivity(lead.company,`Initial email to ${lead.name} needs attention`);save();await flush();return{ok:false,error:lead.initialEmailError}}finally{lead.initialEmailSending=false}}
function scan(){for(const lead of db.leads||[])if(eligible(lead))sendWelcome(lead)}
function settingsHost(){return [...document.querySelectorAll('#more .card')].find(card=>card.querySelector('h2')?.textContent.trim()==='Company Playbook')}
function installSettings(){const host=settingsHost();if(!host||document.getElementById('lwSettings'))return;const wrap=document.createElement('div');wrap.id='lwSettings';wrap.innerHTML=`<hr style="border:0;border-top:1px solid #e5e7eb;margin:20px 0"><h3 style="margin:0 0 5px">New Lead Auto-Reply</h3><p class="muted" style="margin-top:0">Automatically acknowledge brand-new leads that include an email address. Existing leads are never back-emailed.</p><label style="display:flex;align-items:center;gap:10px;margin:12px 0"><input id="lwEnabled" type="checkbox" style="width:auto"> Send an initial email automatically</label><label>Email Subject</label><input id="lwSubject" placeholder="Thanks for contacting {company}"><label>Email Message</label><textarea id="lwMessage" rows="7" placeholder="Thanks for reaching out to {company}!... "></textarea><div class="muted" style="font-size:12px;margin:-3px 0 12px">You can use: {first_name}, {customer}, {company}, {service}</div><button id="lwSave" type="button" class="secondary full">Save Email Settings</button><div id="lwSaved" class="muted" style="font-size:12px;margin-top:8px"></div>`;host.appendChild(wrap);document.getElementById('lwSave').onclick=saveSettings;loadSettings()}
function loadSettings(){const c=currentCompany(),enabled=document.getElementById('lwEnabled'),subject=document.getElementById('lwSubject'),message=document.getElementById('lwMessage');if(!enabled||!subject||!message)return;if(!c){enabled.disabled=subject.disabled=message.disabled=true;return}enabled.disabled=subject.disabled=message.disabled=false;const cfg=emailConfig(c);enabled.checked=cfg.enabled;subject.value=cfg.subject;message.value=cfg.message}
async function saveSettings(){const c=currentCompany(),note=document.getElementById('lwSaved');if(!c){if(note)note.textContent='Select a company first.';return}c.playbook=c.playbook||{};c.playbook.initialEmailEnabled=!!document.getElementById('lwEnabled')?.checked;c.playbook.initialEmailSubject=String(document.getElementById('lwSubject')?.value||'').trim()||defaultSubject(c);c.playbook.initialEmailMessage=String(document.getElementById('lwMessage')?.value||'').trim()||defaultMessage();logActivity(c.id,`Updated new lead auto-reply settings (${c.playbook.initialEmailEnabled?'on':'off'})`);save();await flush();if(note){note.textContent='Saved.';setTimeout(()=>{if(note.textContent==='Saved.')note.textContent=''},1800)}}
function failedLeads(){const a=typeof relevant==='function'?relevant(db.leads||[]):(db.leads||[]);return a.filter(l=>l.initialEmailError&&!l.initialEmailSentAt).slice(0,3)}
function appendFailedActions(){const box=document.getElementById('actionCenter');if(!box)return;for(const lead of failedLeads()){const d=document.createElement('div');d.className='action';const title=document.createElement('strong');title.textContent=`Email ${lead.name}`;const detail=document.createElement('div');detail.className='muted';detail.textContent=`Initial response failed: ${lead.initialEmailError}`;const row=document.createElement('div');row.className='row wrap';const btn=document.createElement('button');btn.className='blue';btn.textContent='Retry Email';btn.onclick=async()=>{btn.disabled=true;btn.textContent='Sending…';const r=await sendWelcome(lead,{force:true});if(r.ok){window.renderActionCenter?.()}else{btn.disabled=false;btn.textContent='Retry Email'}};row.appendChild(btn);d.append(title,detail,row);box.prepend(d)}}
const originalActionCenter=window.renderActionCenter;if(typeof originalActionCenter==='function')window.renderActionCenter=function(){originalActionCenter();appendFailedActions()};
window.officeSendLeadWelcome=(lead)=>sendWelcome(lead,{force:true});
setTimeout(()=>{installSettings();scan();appendFailedActions()},1800);
const select=document.getElementById('companySelect');select?.addEventListener('change',()=>setTimeout(loadSettings,50));
let lastCount=(db.leads||[]).length;setInterval(()=>{installSettings();const n=(db.leads||[]).length;if(n!==lastCount){lastCount=n;scan()}},1200);
})();