(function(){
'use strict';
const ENDPOINT='https://bowrytgqbunodtmzvabp.supabase.co/functions/v1/officeos-send-email';
const el=id=>document.getElementById(id);
const clean=v=>String(v||'').trim();
const escE=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function companyNameFor(id){return (db.companies||[]).find(c=>c.id===id)?.name||'OfficeOS'}
function customerByName(name,companyId){const n=clean(name).toLowerCase();return (db.customers||[]).find(c=>c.company===companyId&&clean(c.name).toLowerCase()===n)||null}
function currentCompanyRef(explicit=''){if(explicit)return explicit;return typeof current==='function'&&current()!=='all'?current():''}
window.officeEmailCompose=function(opts={}){const companyRef=currentCompanyRef(opts.companyRef||''),to=clean(opts.to),name=clean(opts.name),subject=clean(opts.subject),message=clean(opts.message);if(!companyRef)return alert('Select one company first.');if(typeof overlay==='undefined'||typeof formBody==='undefined'||typeof formTitle==='undefined')return alert('OfficeOS email is still loading.');formTitle.textContent=opts.title||'Send Email';formBody.innerHTML=`<div class="item"><div class="kicker">OfficeOS Email</div><h3 style="margin:4px 0">${name?`Email ${escE(name)}`:'Send from OfficeOS'}</h3><div class="muted">This email is sent from the business through OfficeOS. You stay inside the app.</div></div><label>Email Address</label><input id="officeEmailTo" type="email" autocomplete="email" value="${escE(to)}" placeholder="customer@example.com"><label>Subject</label><input id="officeEmailSubject" value="${escE(subject)}" placeholder="Email subject"><label>Message</label><textarea id="officeEmailMessage" rows="9" maxlength="12000" placeholder="Type your message…">${escE(message)}</textarea><div id="officeEmailStatus" class="muted" style="font-size:12px;margin:8px 0"></div><button id="officeEmailSend" class="primary full" type="button" onclick="officeEmailSend('${escE(companyRef)}')">Send Email</button>`;overlay.classList.add('open');setTimeout(()=>el(message?'officeEmailMessage':subject?'officeEmailMessage':'officeEmailSubject')?.focus(),80)};
window.officeEmailSend=async function(companyRef){const to=clean(el('officeEmailTo')?.value),subject=clean(el('officeEmailSubject')?.value),message=clean(el('officeEmailMessage')?.value),btn=el('officeEmailSend'),status=el('officeEmailStatus');if(!to||!to.includes('@'))return alert('Enter a valid email address.');if(!subject)return alert('Enter a subject.');if(!message)return alert('Enter a message.');if(btn){btn.disabled=true;btn.textContent='Sending…'}if(status)status.textContent='Sending securely from OfficeOS…';try{const {data:{session},error}=await supabaseClient.auth.getSession();if(error||!session?.access_token)throw new Error('Please sign in again.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify({companyRef,to,subject,message})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Email could not be sent.');if(status)status.textContent='Sent ✓';if(btn){btn.textContent='Sent ✓';setTimeout(()=>closeForm?.(),650)}return{ok:true,id:d.id||'',to:d.to||to}}catch(e){console.error('[OfficeOS email]',e);if(status)status.textContent=e?.message||'Email could not be sent.';if(btn){btn.disabled=false;btn.textContent='Send Email'}return{ok:false,error:e?.message||'Email could not be sent.'}}};
function commEmail(kind,id){let r=null;if(kind==='lead')r=(db.leads||[]).find(x=>x.id===id);else if(kind==='event')r=(db.events||[]).find(x=>x.id===id);else if(kind==='invoice')r=(db.invoices||[]).find(x=>x.id===id);if(!r)return alert('That record is no longer available.');const companyRef=r.company,business=companyNameFor(companyRef),customerName=r.name||r.customer||'',customer=customerByName(customerName,companyRef),to=r.email||customer?.email||'';if(!to)return alert('Add an email address for this customer first.');let subject='',message='';if(kind==='lead'){subject=`Following up from ${business}`;message=`Hi ${customerName||'there'},\n\nI wanted to follow up regarding ${r.service||'your project'} and see if you have any questions or would like to take the next step.\n\nThank you,\n${business}`}else if(kind==='event'){subject=`Confirming your ${r.type||'appointment'} with ${business}`;message=`Hi ${customerName||'there'},\n\nJust confirming your ${String(r.type||'appointment').toLowerCase()} with ${business}${r.date?` for ${dateText(r.date)}`:''}${r.time?` at ${r.time}`:''}. Please let us know if anything has changed.\n\nThank you,\n${business}`}else{subject=`Message from ${business}`;message=`Hi ${customerName||'there'},\n\n\n\nThank you,\n${business}`}window.officeEmailCompose({companyRef,to,name:customerName,subject,message,title:'Send Customer Email'})}
function installCommunicationOverride(){if(typeof window.officeCommCompose!=='function'||window.officeCommCompose._officeUnified)return false;const old=window.officeCommCompose;const unified=function(kind,id,channel){if(channel==='email')return commEmail(kind,id);return old(kind,id,channel)};unified._officeUnified=true;window.officeCommCompose=unified;return true}
function installContactLinks(){if(typeof window.contactLinks!=='function'||window.contactLinks._officeUnified)return;const unified=function(x){const cid=x?.company||currentCompanyRef(),name=clean(x?.name||x?.customer),phone=clean(x?.phone),email=clean(x?.email);return `<div class="row wrap" style="margin-top:9px">${phone?`<a class="quicklink" href="tel:${escE(phone)}">Call</a><button type="button" class="quicklink" onclick="officeSmsCompose({companyRef:'${escE(cid)}',to:'${escE(phone)}',name:'${escE(name)}',message:'',title:'Send Customer Text'})">Text</button>`:''}${email?`<button type="button" class="quicklink" onclick="officeEmailCompose({companyRef:'${escE(cid)}',to:'${escE(email)}',name:'${escE(name)}',subject:'',message:'',title:'Send Customer Email'})">Email</button>`:''}</div>`};unified._officeUnified=true;window.contactLinks=unified;try{window.renderLeads?.();window.renderOffice?.()}catch{}}
let tries=0;const timer=setInterval(()=>{tries++;installCommunicationOverride();installContactLinks();if(tries>30||((window.officeCommCompose?._officeUnified===true)&&(window.contactLinks?._officeUnified===true)))clearInterval(timer)},150);
setTimeout(()=>{installCommunicationOverride();installContactLinks()},50);
})();