(function(){
const TABS={overview:{label:'Overview',help:'Approvals, activity and plan'},money:{label:'Money',help:'Invoices, estimates and bills'},team:{label:'Team',help:'People, roles and permissions'},business:{label:'Business',help:'Companies, playbook and data'}};
let activeTab='overview',observer=null,busy=false;
function office(){return document.getElementById('more')}
function heading(card){return String(card?.querySelector('h2')?.textContent||'').trim()}
function cardByHeading(text){return [...document.querySelectorAll('#more .card')].find(c=>heading(c)===text)||null}
function ensureHeading(host,id,title,subtitle){let h=document.getElementById(id);if(h)return h;h=document.createElement('div');h.id=id;h.className='relocated-heading';h.innerHTML=`<h2>${title}</h2>${subtitle?`<div class="office-section-note">${subtitle}</div>`:''}`;host.appendChild(h);return h}
function relocate(){const leads=document.getElementById('leads'),dashboard=document.getElementById('dashboard'),settingsHome=document.getElementById('settingsHome');const customers=cardByHeading('Customers');if(customers&&leads&&!customers.dataset.relocated){customers.dataset.relocated='crm';customers.classList.add('relocated-card');ensureHeading(leads,'crmCustomersHeading','Customers','Customer records live with Leads & CRM.').insertAdjacentElement('afterend',customers)}const tasks=cardByHeading('Tasks');if(tasks&&dashboard&&!tasks.dataset.relocated){tasks.dataset.relocated='home';tasks.classList.add('relocated-card');const action=document.getElementById('actionCenter')?.closest('.card');if(action)action.insertAdjacentElement('afterend',tasks);else dashboard.appendChild(tasks)}const account=cardByHeading('Account');if(account&&settingsHome&&!account.dataset.relocated){account.dataset.relocated='settings';account.style.display='none'}}
function category(card){const id=card.id||'',h=heading(card).toLowerCase();if(id==='permissionsOverviewCard'||id==='teamPermissionsCard'||h.includes('team')||h.includes('permission'))return'team';if(id==='payablesCard'||h.includes('invoice')||h.includes('estimate')||h.includes('bill')||h.includes('payment')||h.includes('finance'))return'money';if(id==='jobTemplateLibrary'||h.includes('playbook')||h==='companies'||h==='data'||h.includes('template'))return'business';return'overview'}
function ensureNav(){const o=office();if(!o)return null;let nav=document.getElementById('officeSubnav');if(nav)return nav;nav=document.createElement('div');nav.id='officeSubnav';nav.className='office-subnav';nav.setAttribute('role','tablist');nav.innerHTML=Object.entries(TABS).map(([key,t])=>`<button type="button" class="office-tab ${key===activeTab?'active':''}" data-office-tab="${key}" onclick="officeShowTab('${key}')">${t.label}</button>`).join('');o.querySelector('h1')?.insertAdjacentElement('afterend',nav);return nav}
function ensureContext(){const o=office();if(!o)return null;let ctx=document.getElementById('officeTabContext');if(ctx)return ctx;ctx=document.createElement('div');ctx.id='officeTabContext';ctx.className='office-tab-context';o.querySelector('#officeSubnav')?.insertAdjacentElement('afterend',ctx);return ctx}
function apply(){if(busy)return;busy=true;try{relocate();const nav=ensureNav(),ctx=ensureContext(),o=office();if(!o)return;[...o.children].forEach(node=>{if(!node.classList?.contains('card'))return;if(node.dataset.relocated)return;node.dataset.officeTab=category(node);node.classList.toggle('office-panel-hidden',node.dataset.officeTab!==activeTab)});nav?.querySelectorAll('button').forEach(b=>{const on=b.dataset.officeTab===activeTab;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false')});if(ctx)ctx.textContent=TABS[activeTab]?.help||''}finally{busy=false}}
window.officeShowTab=function(tab){if(!TABS[tab])return;activeTab=tab;apply();const o=office();if(o?.classList.contains('active')){const y=(document.getElementById('officeSubnav')?.getBoundingClientRect().top||0)+window.scrollY-8;window.scrollTo({top:Math.max(0,y),behavior:'auto'})}}
function install(){apply();if(observer)return;observer=new MutationObserver(()=>setTimeout(apply,0));observer.observe(document.body,{childList:true,subtree:true});document.querySelector('nav button[data-page="more"]')?.addEventListener('click',()=>setTimeout(apply,0));document.querySelector('nav button[data-page="leads"]')?.addEventListener('click',()=>setTimeout(relocate,0));document.querySelector('nav button[data-page="dashboard"]')?.addEventListener('click',()=>setTimeout(relocate,0))}
setTimeout(install,1600);
})();