(function(){
function ensureFinance(){if(!Array.isArray(db.payables))db.payables=[]}
function relevantPayables(){ensureFinance();return current()==='all'?db.payables:db.payables.filter(x=>x.company===current())}
function payableCompanyOptions(selected){return (db.companies||[]).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function payableForm(x=null){ensureFinance();const today=new Date().toISOString().slice(0,10),cid=x?.company||(current()==='all'?(db.companies[0]?.id||''):current());formTitle.textContent=x?'Edit Bill':'Add Bill';formBody.innerHTML=`<label>Company</label><select id="payCompany">${payableCompanyOptions(cid)}</select><label>Vendor / Payee</label><input id="payVendor" value="${esc(x?.vendor||'')}" placeholder="Vendor name"><div class="row"><div style="flex:1"><label>Amount</label><input id="payAmount" type="number" min="0" step="0.01" value="${Number(x?.amount||0)}"></div><div style="flex:1"><label>Status</label><select id="payStatus"><option ${x?.status!=='Paid'?'selected':''}>Open</option><option ${x?.status==='Paid'?'selected':''}>Paid</option></select></div></div><div class="row"><div style="flex:1"><label>Bill Date</label><input id="payBillDate" type="date" value="${x?.billDate||today}"></div><div style="flex:1"><label>Due Date</label><input id="payDueDate" type="date" value="${x?.dueDate||today}"></div></div><label>Category</label><input id="payCategory" value="${esc(x?.category||'')}" placeholder="Materials, utilities, subcontractor..."><label>Reference / Bill #</label><input id="payReference" value="${esc(x?.reference||'')}"><label>Notes</label><textarea id="payNotes">${esc(x?.notes||'')}</textarea><button class="primary full" onclick="savePayable('${x?.id||''}')">Save Bill</button>`;overlay.classList.add('open')}
window.openPayable=function(id=''){const x=id?db.payables.find(v=>v.id===id):null;payableForm(x)}
window.savePayable=function(id=''){ensureFinance();const vendor=document.getElementById('payVendor').value.trim(),amount=Number(document.getElementById('payAmount').value||0);if(!vendor)return alert('Enter a vendor or payee.');if(amount<0)return alert('Amount cannot be negative.');const old=db.payables.find(v=>v.id===id),x={id:id||uid(),company:payCompany.value,vendor,amount,status:payStatus.value,billDate:payBillDate.value,dueDate:payDueDate.value,category:payCategory.value.trim(),reference:payReference.value.trim(),notes:payNotes.value.trim(),paidAt:payStatus.value==='Paid'?(old?.paidAt||nowISO()):'',createdAt:old?.createdAt||nowISO(),updatedAt:nowISO()};if(id)db.payables=db.payables.map(v=>v.id===id?x:v);else db.payables.push(x);logActivity(x.company,`${id?'Updated':'Added'} bill from ${x.vendor} for ${money(x.amount)}`);closeForm();save()}
window.markPayablePaid=function(id){const x=db.payables.find(v=>v.id===id);if(!x)return;x.status='Paid';x.paidAt=nowISO();x.updatedAt=nowISO();logActivity(x.company,`Marked bill from ${x.vendor} paid`);save()}
window.deletePayable=function(id){const x=db.payables.find(v=>v.id===id);if(!x)return;const needs=window.officeSettings?.().confirmDeletes!==false;if(needs&&!confirm(`Delete the bill from ${x.vendor}?`))return;db.payables=db.payables.filter(v=>v.id!==id);logActivity(x.company,`Deleted bill from ${x.vendor}`);save()}
function payableCard(){const a=relevantPayables(),today=new Date().toISOString().slice(0,10),open=a.filter(x=>x.status!=='Paid'),overdue=open.filter(x=>x.dueDate&&x.dueDate<today),sum=v=>v.reduce((t,x)=>t+Number(x.amount||0),0);return `<div class="card" id="payablesCard"><div class="section-title"><div><div class="kicker">Money Out</div><h2>Bills & Payables</h2></div><button class="primary" onclick="openPayable()">+ Bill</button></div><div class="payable-summary"><div><b>${money(sum(open))}</b><span>Open</span></div><div><b>${money(sum(overdue))}</b><span>Overdue</span></div></div><div id="payableList">${a.length?a.slice().sort((x,y)=>(x.status==='Paid')-(y.status==='Paid')||(x.dueDate||'9999').localeCompare(y.dueDate||'9999')).map(x=>`<div class="item ${x.status==='Paid'?'good':(x.dueDate&&x.dueDate<today?'urgent':'')}"><div class="row between"><div><div class="item-title">${esc(x.vendor)}</div><div class="muted">${esc(x.category||'Bill')}${x.reference?` • ${esc(x.reference)}`:''}</div></div><div class="money">${money(x.amount)}</div></div><span class="tag">${esc(x.status||'Open')}</span>${x.dueDate?`<span class="tag">Due ${dateText(x.dueDate)}</span>`:''}${current()==='all'?`<span class="tag">${esc(companyName(x.company))}</span>`:''}${x.notes?`<p class="muted">${esc(x.notes)}</p>`:''}<div class="row wrap" style="margin-top:9px"><button class="secondary" onclick="openPayable('${x.id}')">Edit</button>${x.status!=='Paid'?`<button class="success" onclick="markPayablePaid('${x.id}')">Mark Paid</button>`:''}<button class="danger" onclick="deletePayable('${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No bills or payables yet.</div>'}</div></div>`}
function renderPayables(){ensureFinance();const invoiceList=document.getElementById('invoiceList'),invoiceCard=invoiceList?.closest('.card'),existing=document.getElementById('payablesCard');if(existing)existing.remove();if(invoiceCard)invoiceCard.insertAdjacentHTML('afterend',payableCard())}
const oldRenderOffice=window.renderOffice;window.renderOffice=function(){const r=oldRenderOffice.apply(this,arguments);renderPayables();return r}
setTimeout(renderPayables,500);
})();