(function(){
'use strict';
const ENDPOINT='https://bowrytgqbunodtmzvabp.supabase.co/functions/v1/officeos-send-sms';
const el=id=>document.getElementById(id);
function currentCompanyRef(explicit=''){if(explicit)return explicit;return typeof current==='function'&&current()!=='all'?current():''}
function escS(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function normalize(v){return String(v||'').trim()}
window.officeSmsCompose=function(opts={}){const companyRef=currentCompanyRef(opts.companyRef||''),to=normalize(opts.to),message=normalize(opts.message),name=normalize(opts.name);if(!companyRef)return alert('Select one company first.');if(typeof overlay==='undefined'||typeof formBody==='undefined'||typeof formTitle==='undefined')return alert('OfficeOS messaging is still loading.');formTitle.textContent=opts.title||'Send Text';formBody.innerHTML=`<div class="item"><div class="kicker">OfficeOS Texting</div><h3 style="margin:4px 0">${name?`Text ${escS(name)}`:'Send from OfficeOS'}</h3><div class="muted">The message is sent from the business messaging number. You stay inside OfficeOS.</div></div><label>Phone Number</label><input id="officeSmsTo" type="tel" inputmode="tel" autocomplete="tel" value="${escS(to)}" placeholder="Customer phone number"><label>Message</label><textarea id="officeSmsMessage" rows="7" maxlength="1200" placeholder="Type your message…">${escS(message)}</textarea><div id="officeSmsStatus" class="muted" style="font-size:12px;margin:8px 0"></div><button id="officeSmsSend" class="primary full" type="button" onclick="officeSmsSend('${escS(companyRef)}')">Send Text</button>`;overlay.classList.add('open');setTimeout(()=>el(to?'officeSmsMessage':'officeSmsTo')?.focus(),80)};
window.officeSmsSend=async function(companyRef){const to=normalize(el('officeSmsTo')?.value),message=normalize(el('officeSmsMessage')?.value),btn=el('officeSmsSend'),status=el('officeSmsStatus');if(!to)return alert('Enter a phone number.');if(!message)return alert('Enter a message.');if(btn){btn.disabled=true;btn.textContent='Sending…'}if(status)status.textContent='Sending securely from OfficeOS…';try{const {data:{session},error}=await supabaseClient.auth.getSession();if(error||!session?.access_token)throw new Error('Please sign in again.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify({to,message,companyRef})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Text could not be sent.');if(status)status.textContent='Sent ✓';if(btn){btn.textContent='Sent ✓';setTimeout(()=>closeForm?.(),650)}return{ok:true,id:d.id||'',status:d.status||'queued',to:d.to||to}}catch(e){console.error('[OfficeOS SMS]',e);if(status)status.textContent=e?.message||'Text could not be sent.';if(btn){btn.disabled=false;btn.textContent='Send Text'}return{ok:false,error:e?.message||'Text could not be sent.'}}};
})();