(function(){
const OFFICE_JUMPS=[['money','Money'],['communications','Messages'],['approvals','Approvals'],['activity','Activity'],['playbook','Playbook'],['team','Team & Payroll'],['companies','Companies']];
const SETTINGS_JUMPS=[['account','Account'],['security','Security'],['data','Data'],['workflow','Workflow'],['app','App Settings']];
let observer=null,busy=false;
function office(){return document.getElementById('more')}
function settingsPage(){return document.getElementById('settings')}
function heading(card){return String(card?.querySelector('h2')?.textContent||'').trim()}
function officeCards(){return [...document.querySelectorAll('#more .card')]}
function firstOffice(fn){return officeCards().find(fn)||null}
function ensureHeading(host,id,title,subtitle){let h=document.getElementById(id);if(h)return h;h=document.createElement('div');h.id=id;h.className='relocated-heading';h.innerHTML=`<h2>${title}</h2>${subtitle?`<div class="office-section-note">${subtitle}</div>`:''}`;host.appendChild(h);return h}
function ensureSettingsHost(){const page=settingsPage();if(!page)return null;let host=document.getElementById('settingsOrganized');if(host)return host;host=document.createElement('div');host.id='settingsOrganized';document.getElementById('settingsHome')?.insertAdjacentElement('afterend',host);return host}
function relocate(){const leads=document.getElementById('leads'),dashboard=document.getElementById('dashboard'),settingsHost=ensureSettingsHost();const customers=officeCards().find(c=>heading(c)==='Customers');if(customers&&leads&&!customers.dataset.relocated){customers.dataset.relocated='crm';customers.classList.add('relocated-card');ensureHeading(leads,'crmCustomersHeading','Customers','Customer records live with Leads & CRM.').insertAdjacentElement('afterend',customers)}const tasks=officeCards().find(c=>heading(c)==='Tasks');if(tasks&&dashboard&&!tasks.dataset.relocated){tasks.dataset.relocated='home';tasks.classList.add('relocated-card');const action=document.getElementById('actionCenter')?.closest('.card');if(action)action.insertAdjacentElement('afterend',tasks);else dashboard.appendChild(tasks)}const account=officeCards().find(c=>heading(c)==='Account');if(account&&!account.dataset.relocated){account.dataset.relocated='settings-duplicate';account.style.display='none'}const data=officeCards().find(c=>heading(c)==='Data');if(data&&settingsHost&&data.parentElement!==settingsHost){data.dataset.relocated='settings';data.classList.add('relocated-card');settingsHost.appendChild(data)}const security=document.getElementById('officeSecurityCenter');if(security&&settingsHost&&security.parentElement!==settingsHost){security.dataset.relocated='settings';security.classList.add('relocated-card');settingsHost.insertBefore(security,settingsHost.firstChild)}}
function officeTarget(key){if(key==='money')return firstOffice(c=>/invoice|estimate|bill|payment|finance/i.test(heading(c))||c.id==='payablesCard');if(key==='communications')return document.getElementById('communicationsSection');if(key==='approvals')return firstOffice(c=>/^approvals$/i.test(heading(c)));if(key==='activity')return firstOffice(c=>/recent activity|activity/i.test(heading(c)));if(key==='playbook')return firstOffice(c=>/playbook/i.test(heading(c)));if(key==='team')return document.getElementById('teamPayrollSection');if(key==='companies')return firstOffice(c=>/^companies$/i.test(heading(c)));return null}
function settingsTarget(key){const page=settingsPage();if(!page)return null;if(key==='account')return document.querySelector('#settingsHome .card');if(key==='security')return document.getElementById('officeSecurityCenter')||document.getElementById('sg-security');if(key==='data')return document.getElementById('officeImportCenter')||[...page.querySelectorAll('.card')].find(c=>heading(c)==='Data')||null;if(key==='workflow')return document.getElementById('pbPhotoPolicy')||document.getElementById('pbCompletionInvoicePolicy');if(key==='app')return page.querySelector('.settings-shell');return null}
function makeNav(id,items,handler,label){let nav=document.getElementById(id);if(nav)return nav;const page=id==='officeJumpNav'?office():settingsPage();if(!page)return null;nav=document.createElement('div');nav.id=id;nav.className='office-jump-nav';nav.setAttribute('aria-label',label);nav.innerHTML=items.map(([key,text])=>`<button type="button" class="office-jump-btn" data-jump="${key}" onclick="${handler}('${key}')">${text}</button>`).join('');page.querySelector('h1')?.insertAdjacentElement('afterend',nav);return nav}
function refreshNav(nav,items,targetFn){if(!nav)return;for(const [key]of items){let btn=nav.querySelector(`[data-jump="${key}"]`);if(!btn){btn=document.createElement('button');btn.type='button';btn.className='office-jump-btn';btn.dataset.jump=key;btn.textContent=items.find(x=>x[0]===key)?.[1]||key;btn.onclick=()=>id==='officeJumpNav'?window.officeJumpTo(key):window.settingsJumpTo(key);nav.appendChild(btn)}btn.hidden=!targetFn(key)}}
function jump(target,nav,key){if(!target)return;nav?.querySelectorAll('.office-jump-btn').forEach(b=>b.classList.toggle('active',b.dataset.jump===key));const y=target.getBoundingClientRect().top+window.scrollY-(nav?.offsetHeight||52)-12;window.scrollTo({top:Math.max(0,y),behavior:'smooth'});target.classList.add('office-jump-focus');setTimeout(()=>target.classList.remove('office-jump-focus'),900)}
window.officeJumpTo=function(key){jump(officeTarget(key),document.getElementById('officeJumpNav'),key)};window.settingsJumpTo=function(key){jump(settingsTarget(key),document.getElementById('settingsJumpNav'),key)};
function ensureNavButtons(nav,items,handler){if(!nav)return;for(const [key,text] of items){if(nav.querySelector(`[data-jump="${key}"]`))continue;const btn=document.createElement('button');btn.type='button';btn.className='office-jump-btn';btn.dataset.jump=key;btn.textContent=text;btn.onclick=()=>window[handler](key);nav.appendChild(btn)}}
function apply(){if(busy)return;busy=true;try{relocate();const on=makeNav('officeJumpNav',OFFICE_JUMPS,'officeJumpTo','Office page navigation'),sn=makeNav('settingsJumpNav',SETTINGS_JUMPS,'settingsJumpTo','Settings page navigation');ensureNavButtons(on,OFFICE_JUMPS,'officeJumpTo');ensureNavButtons(sn,SETTINGS_JUMPS,'settingsJumpTo');for(const [key]of OFFICE_JUMPS){const btn=on?.querySelector(`[data-jump="${key}"]`);if(btn)btn.hidden=!officeTarget(key)}for(const [key]of SETTINGS_JUMPS){const btn=sn?.querySelector(`[data-jump="${key}"]`);if(btn)btn.hidden=!settingsTarget(key)}}finally{busy=false}}
window.refreshOfficeOrganization=apply;function install(){apply();if(observer)return;observer=new MutationObserver(()=>setTimeout(apply,0));observer.observe(document.body,{childList:true,subtree:true});document.querySelector('nav button[data-page="more"]')?.addEventListener('click',()=>setTimeout(()=>{apply();window.scrollTo({top:0,behavior:'auto'})},0));document.querySelector('nav button[data-page="settings"]')?.addEventListener('click',()=>setTimeout(()=>{apply();window.scrollTo({top:0,behavior:'auto'})},0))}setTimeout(install,900);
})();