(function(){
const VERSION='18';
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function exportBackup(){const stamp=new Date().toISOString().slice(0,10);download(`OfficeOS-backup-${stamp}.json`,JSON.stringify(db,null,2),'application/json')}
function exportCustomers(){const rows=[['Company','Customer','Phone','Email','Address'],...(db.customers||[]).map(x=>[companyName(x.company),x.name||'',x.phone||'',x.email||'',x.address||''])];download('OfficeOS-customers.csv',rows.map(r=>r.map(csvEscape).join(',')).join('\n'),'text/csv')}
function exportInvoices(){const rows=[['Company','Invoice','Customer','Email','Issue Date','Due Date','Status','Amount'],...(db.invoices||[]).map(x=>[companyName(x.company),x.number||'',x.customer||'',x.email||'',x.issueDate||'',x.dueDate||'',x.status||'',Number(x.amount||0).toFixed(2)])];download('OfficeOS-invoices.csv',rows.map(r=>r.map(csvEscape).join(',')).join('\n'),'text/csv')}
function exportJobs(){const rows=[['Company','Customer','Job','Status','Date','Amount','Address'],...(db.jobs||[]).map(x=>[companyName(x.company),x.customer||'',x.title||'',x.status||'',x.date||'',Number(x.amount||0).toFixed(2),x.address||''])];download('OfficeOS-jobs.csv',rows.map(r=>r.map(csvEscape).join(',')).join('\n'),'text/csv')}
window.officeExportBackup=exportBackup;window.officeExportCustomers=exportCustomers;window.officeExportInvoices=exportInvoices;window.officeExportJobs=exportJobs;
function autoOverdue(){const today=new Date().toISOString().slice(0,10);let changed=false;for(const x of db.invoices||[]){if((x.type==='Invoice'||!x.type)&&x.status!=='Paid'&&x.status!=='Draft'&&x.dueDate&&x.dueDate<today&&x.status!=='Overdue'){x.status='Overdue';x.updatedAt=nowISO();logActivity(x.company,`Invoice ${x.number||''} became overdue`);changed=true}}if(changed){localStorage.setItem(KEY,JSON.stringify(db));cloudSave();}}
function enhanceStats(){document.querySelectorAll('.stats .stat').forEach(el=>{el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',el.innerText.replace(/\s+/g,' ').trim());if(!el.dataset.keywired){el.dataset.keywired='1';el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}})}})}
function updateNetwork(){const dot=document.getElementById('officeNetDot'),text=document.getElementById('officeNetText');if(!dot||!text)return;const online=navigator.onLine;dot.classList.toggle('offline',!online);const next=online?'Online':'Offline — local copy available';if(text.textContent!==next)text.textContent=next}
function addOfficeTools(){const more=document.getElementById('more');if(!more||document.getElementById('officeDataTools'))return;const card=document.createElement('div');card.className='card';card.id='officeDataTools';card.innerHTML=`<h2>Backups & Exports</h2><p class="muted">Keep a portable copy of your business data anytime.</p><div class="data-tools"><button class="secondary" onclick="officeExportCustomers()">Export Customers CSV</button><button class="secondary" onclick="officeExportInvoices()">Export Invoices CSV</button><button class="secondary" onclick="officeExportJobs()">Export Jobs CSV</button><button class="primary" onclick="officeExportBackup()">Download Full Backup</button></div><div class="backup-note">Your cloud sync continues to work normally. These downloads are extra copies you control.</div><div class="app-health"><span class="health-pill"><span id="officeNetDot" class="health-dot"></span><span id="officeNetText">Online</span></span><span class="health-pill">OfficeOS v${VERSION}</span></div>`;more.appendChild(card);updateNetwork()}
function plusRender(){enhanceStats();addOfficeTools();updateNetwork();addInstallCard()}
const oldRender=window.render;window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(plusRender,0);return r}
const oldRenderOffice=window.renderOffice;window.renderOffice=function(){const r=oldRenderOffice.apply(this,arguments);setTimeout(plusRender,0);return r}
const oldOpenForm=window.openForm;window.openForm=function(type,data=null){const r=oldOpenForm(type,data);if(type==='invoice')setTimeout(()=>enhanceInvoiceForm(data),0);return r}
function enhanceInvoiceForm(data){const customer=document.getElementById('fCustomer'),email=document.getElementById('fInvEmail'),due=document.getElementById('fDueDate'),issue=document.getElementById('fIssueDate');if(!customer)return;if(!data&&issue&&due&&issue.value&&due.value===issue.value){const d=new Date(issue.value+'T12:00:00');d.setDate(d.getDate()+30);due.value=d.toISOString().slice(0,10)}let dl=document.getElementById('officeCustomerNames');if(!dl){dl=document.createElement('datalist');dl.id='officeCustomerNames';document.body.appendChild(dl)}dl.innerHTML=(db.customers||[]).map(c=>`<option value="${esc(c.name)}"></option>`).join('');customer.setAttribute('list','officeCustomerNames');customer.addEventListener('change',()=>{const c=(db.customers||[]).find(v=>v.name?.toLowerCase()===customer.value.trim().toLowerCase()&&(!document.getElementById('fCompany')||v.company===document.getElementById('fCompany').value));if(c&&email&&!email.value)email.value=c.email||''});const lines=document.getElementById('invoiceLines');if(lines&&!document.getElementById('invoiceHelper')){const n=document.createElement('div');n.id='invoiceHelper';n.className='invoice-helper';n.textContent='Tip: choose an existing customer name to automatically fill their saved email. New invoices default to Net 30.';lines.parentElement.insertBefore(n,lines)}}
const oldSaveInvoice=window.saveProfessionalInvoice;window.saveProfessionalInvoice=function(id){const number=document.getElementById('fInvNumber'),email=document.getElementById('fInvEmail');[number,email].forEach(x=>x?.classList.remove('field-error'));if(number){const n=number.value.trim().toLowerCase();const dupe=(db.invoices||[]).find(x=>x.id!==id&&String(x.number||'').trim().toLowerCase()===n);if(dupe){number.classList.add('field-error');return alert('That invoice number already exists. Use a unique invoice number.')}}if(email&&email.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value)){email.classList.add('field-error');return alert('Enter a valid customer email address.')}const rows=[...document.querySelectorAll('#invoiceLines .invoice-row')];if(rows.length&&!rows.some(r=>r.querySelector('.li-desc')?.value.trim()&&Number(r.querySelector('.li-qty')?.value||0)>0)){return alert('Add at least one invoice line with a description and quantity.')}return oldSaveInvoice(id)}
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.officeInstall=async function(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else alert('On iPhone: tap the Share button, then choose “Add to Home Screen” to install OfficeOS like an app.')}
function addInstallCard(){const more=document.getElementById('more');if(!more||document.getElementById('officeInstallCard')||window.matchMedia('(display-mode: standalone)').matches)return;const card=document.createElement('div');card.className='card install-card';card.id='officeInstallCard';card.innerHTML='<h2>Install OfficeOS</h2><p class="muted">Put OfficeOS on your home screen for faster, app-like access.</p><button class="primary full" onclick="officeInstall()">Add OfficeOS to Home Screen</button>';more.appendChild(card)}
window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js?v=18').catch(()=>{}));
setTimeout(()=>{autoOverdue();plusRender()},600);
})();