(function(){
'use strict';
const el=id=>document.getElementById(id);
function ensure(){db.employees=Array.isArray(db.employees)?db.employees:[];db.timeEntries=Array.isArray(db.timeEntries)?db.timeEntries:[];db.payrollRuns=Array.isArray(db.payrollRuns)?db.payrollRuns:[]}
function cid(){return typeof current==='function'&&current()!=='all'?current():(db.companies?.[0]?.id||'')}
function money2(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
function relevantEmployees(){const c=cid();return (db.employees||[]).filter(x=>x.company===c&&x.active!==false)}
function relevantTime(){const c=cid();return (db.timeEntries||[]).filter(x=>x.company===c)}
function period(){const today=new Date(),end=today.toISOString().slice(0,10),start=new Date(today);start.setDate(start.getDate()-13);return{start:start.toISOString().slice(0,10),end}}
function hoursFor(emp,start,end){return relevantTime().filter(x=>x.employeeId===emp.id&&x.date>=start&&x.date<=end).reduce((s,x)=>s+Number(x.hours||0),0)}
function otFor(emp,start,end){return relevantTime().filter(x=>x.employeeId===emp.id&&x.date>=start&&x.date<=end).reduce((s,x)=>s+Number(x.overtimeHours||0),0)}
function grossFor(emp,start,end){if(emp.payType==='salary')return Number(emp.rate||0)/26;const h=hoursFor(emp,start,end),ot=otFor(emp,start,end),regular=Math.max(0,h-ot);return regular*Number(emp.rate||0)+ot*Number(emp.rate||0)*1.5}
function render(){ensure();const host=el('payrollCenter');if(!host)return;const p=period(),emps=relevantEmployees(),gross=emps.reduce((s,e)=>s+grossFor(e,p.start,p.end),0),hours=emps.reduce((s,e)=>s+hoursFor(e,p.start,p.end),0);host.innerHTML=`<div class="card"><div class="row between"><div><div class="kicker">Team</div><h2>Employees</h2></div><button class="primary" onclick="officeAddEmployee()">+ Employee</button></div>${emps.length?emps.map(e=>`<div class="item"><div class="row between"><div><b>${esc(e.name)}</b><div class="muted">${esc(e.role||'Team member')} · ${e.payType==='salary'?money2(e.rate)+'/yr':money2(e.rate)+'/hr'}</div></div><span class="tag">${e.payType==='salary'?'Salary':'Hourly'}</span></div><div class="row wrap" style="margin-top:8px"><button class="secondary" onclick="officeAddTime('${e.id}')">+ Time</button><button class="secondary" onclick="officeEditEmployee('${e.id}')">Edit</button></div></div>`).join(''):'<div class="empty">Add employees to start tracking time and preparing payroll.</div>'}</div><div class="card"><div class="row between"><div><div class="kicker">Payroll</div><h2>Payroll Ready</h2></div><span class="tag">${p.start} → ${p.end}</span></div><div class="stats" style="margin-top:12px"><div class="stat"><strong>${emps.length}</strong><span>Employees</span></div><div class="stat"><strong>${hours.toFixed(1)}</strong><span>Hours</span></div><div class="stat"><strong>${money2(gross)}</strong><span>Est. Gross</span></div></div><div class="muted" style="margin:12px 0">OfficeOS prepares payroll totals here. Final direct deposit, withholding and tax filing will be handed to a connected payroll provider.</div>${emps.length?emps.map(e=>`<div class="item"><div class="row between"><div><b>${esc(e.name)}</b><div class="muted">${e.payType==='salary'?'Salary':hoursFor(e,p.start,p.end).toFixed(1)+' hrs'}${otFor(e,p.start,p.end)?` · ${otFor(e,p.start,p.end).toFixed(1)} OT`:''}</div></div><b>${money2(grossFor(e,p.start,p.end))}</b></div></div>`).join(''):''}<button class="primary full" ${emps.length?'':'disabled'} onclick="officePreparePayroll()">Prepare Payroll Run</button></div><div class="card"><h2>Recent Payroll Runs</h2>${(db.payrollRuns||[]).filter(x=>x.company===cid()).slice(0,5).map(r=>`<div class="item"><div class="row between"><div><b>${r.start} → ${r.end}</b><div class="muted">${r.employeeCount} employees · ${Number(r.hours||0).toFixed(1)} hours</div></div><b>${money2(r.gross)}</b></div><span class="tag">${esc(r.status||'Prepared')}</span></div>`).join('')||'<div class="muted">No payroll runs prepared yet.</div>'}</div>`}
function mount(){ensure();const office=el('more');if(!office)return;let section=el('teamPayrollSection');if(!section){section=document.createElement('div');section.id='teamPayrollSection';section.innerHTML='<div class="relocated-heading"><h2>Team & Payroll</h2><div class="office-section-note">Employees, secure access, time and payroll preparation.</div></div><div id="payrollCenter"></div>';const companies=[...office.querySelectorAll('.card')].find(c=>c.querySelector('h2')?.textContent.trim()==='Companies');if(companies)companies.insertAdjacentElement('beforebegin',section);else office.appendChild(section)}render();window.refreshOfficeOrganization?.()}
function promptEmployee(existing){const name=prompt('Employee name',existing?.name||'');if(!name)return null;const role=prompt('Role / title',existing?.role||'Installer')||'';const payType=(prompt('Pay type: hourly or salary',existing?.payType||'hourly')||'hourly').toLowerCase()==='salary'?'salary':'hourly';const rate=Number(prompt(payType==='salary'?'Annual salary':'Hourly rate',String(existing?.rate||''))||0);if(rate<0||!Number.isFinite(rate))return alert('Enter a valid pay rate.'),null;return{name:name.trim(),role:role.trim(),payType,rate}}
window.officeAddEmployee=function(){const c=cid();if(!c)return alert('Choose a company first.');const x=promptEmployee();if(!x)return;db.employees.unshift({id:uid(),company:c,...x,active:true,createdAt:nowISO(),updatedAt:nowISO()});logActivity(c,`Added employee ${x.name}`);save();render()}
window.officeEditEmployee=function(id){const e=db.employees.find(x=>x.id===id);if(!e)return;const x=promptEmployee(e);if(!x)return;Object.assign(e,x,{updatedAt:nowISO()});logActivity(e.company,`Updated employee ${e.name}`);save();render()}
window.officeAddTime=function(id){const e=db.employees.find(x=>x.id===id);if(!e)return;const date=prompt('Work date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!date)return;const hours=Number(prompt('Total hours worked','8')||0),ot=Number(prompt('Overtime hours included in total','0')||0);if(!Number.isFinite(hours)||hours<0||!Number.isFinite(ot)||ot<0||ot>hours)return alert('Check the hours and overtime amounts.');const jobs=(db.jobs||[]).filter(j=>j.company===e.company);const jobText=jobs.slice(0,8).map((j,i)=>`${i+1}. ${j.customer} — ${j.title}`).join('\n');let jobId='';if(jobs.length&&confirm('Attach these hours to a job?')){const pick=Number(prompt(`Choose job number:\n${jobText}`,'1'));if(pick>=1&&pick<=Math.min(8,jobs.length))jobId=jobs[pick-1].id}db.timeEntries.unshift({id:uid(),company:e.company,employeeId:e.id,date,hours,overtimeHours:ot,jobId,createdAt:nowISO(),updatedAt:nowISO()});logActivity(e.company,`Added ${hours} hours for ${e.name}`);save();render()}
window.officePreparePayroll=function(){const c=cid(),p=period(),emps=relevantEmployees();if(!c||!emps.length)return;const run={id:uid(),company:c,start:p.start,end:p.end,employeeCount:emps.length,hours:emps.reduce((s,e)=>s+hoursFor(e,p.start,p.end),0),gross:emps.reduce((s,e)=>s+grossFor(e,p.start,p.end),0),status:'Prepared',createdAt:nowISO(),lines:emps.map(e=>({employeeId:e.id,name:e.name,hours:hoursFor(e,p.start,p.end),overtimeHours:otFor(e,p.start,p.end),gross:grossFor(e,p.start,p.end)}))};db.payrollRuns.unshift(run);logActivity(c,`Prepared payroll run for ${run.employeeCount} employees · ${money2(run.gross)} gross`);save();render();alert('Payroll run prepared for review. No money has been moved yet.')}
function loadTeamAssets(){if(!document.querySelector('link[data-team-access-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='team-access.css?v=1';l.dataset.teamAccessCss='1';document.head.appendChild(l)}if(!document.querySelector('link[data-employee-workspace-css]')){const l=document.createElement('link');l.rel='stylesheet';l.href='employee-workspace.css?v=1';l.dataset.employeeWorkspaceCss='1';document.head.appendChild(l)}if(!document.querySelector('script[data-team-access]')){const s=document.createElement('script');s.src='team-access.js?v=1';s.defer=true;s.dataset.teamAccess='1';document.body.appendChild(s)}if(!document.querySelector('script[data-employee-workspace]')){const s=document.createElement('script');s.src='employee-workspace.js?v=1';s.defer=true;s.dataset.employeeWorkspace='1';document.body.appendChild(s)}}
document.getElementById('companySelect')?.addEventListener('change',()=>setTimeout(render,0));
loadTeamAssets();setTimeout(mount,1500);const baseRender=window.render;if(typeof baseRender==='function')window.render=function(){const r=baseRender.apply(this,arguments);setTimeout(mount,0);return r};
})();