(function(){
'use strict';
const SITE='https://officeospro.com/';
const REMEMBER_KEY='officeos_remember_device';
const SESSION_ONLY_KEY='officeos_session_only';
const LAST_VERIFY_KEY='officeos_last_session_verify';
const el=id=>document.getElementById(id);
function remembered(){return localStorage.getItem(REMEMBER_KEY)!=='0'}
function stamp(){const raw=localStorage.getItem(LAST_VERIFY_KEY);if(!raw)return'Not checked yet';const d=new Date(raw);return Number.isNaN(d.getTime())?'Not checked yet':d.toLocaleString()}
function statusMarkup(){return `<div class="card" id="officeSecurityCenter"><div class="row between"><div><div class="kicker">Security Center</div><h2>Account & Device</h2></div><span class="sync ok">Protected</span></div><div class="item"><div class="row between"><div><b>Secure connection</b><div class="muted">${location.protocol==='https:'?'HTTPS is active on officeospro.com':'This connection is not secure'}</div></div><span>${location.protocol==='https:'?'🔒':'⚠️'}</span></div></div><div class="item"><div class="row between"><div><b>Remember this device</b><div class="muted">${remembered()?'This trusted device can keep you signed in.':'This device uses a temporary sign-in.'}</div></div><span class="tag">${remembered()?'On':'Off'}</span></div></div><div class="item"><b>Session verification</b><div class="muted">Last checked: <span id="officeLastVerify">${stamp()}</span></div></div><button class="secondary full" onclick="officeVerifySessionNow()">Verify My Session</button><button class="secondary full" style="margin-top:8px" onclick="officeSendPasswordReset()">Send Password Reset Email</button><button class="danger full" style="margin-top:8px" onclick="officeForgetThisDevice()">Forget This Device</button><p class="muted" style="margin-top:10px">For shared or public devices, turn off “Remember me” at sign-in or use Forget This Device when finished.</p></div>`}
function install(){const more=el('more');if(!more||el('officeSecurityCenter'))return;const account=[...more.querySelectorAll('.card')].find(c=>c.querySelector('h2')?.textContent.trim()==='Account');if(account)account.insertAdjacentHTML('afterend',statusMarkup());else more.insertAdjacentHTML('afterbegin',statusMarkup())}
window.officeVerifySessionNow=async function(){if(!window.supabaseClient?.auth)return alert('Security check is unavailable.');const btn=document.activeElement;if(btn?.tagName==='BUTTON')btn.disabled=true;try{const {data,error}=await supabaseClient.auth.getUser();if(error||!data?.user)throw error||new Error('Session expired');const now=new Date().toISOString();localStorage.setItem(LAST_VERIFY_KEY,now);const label=el('officeLastVerify');if(label)label.textContent=new Date(now).toLocaleString();alert('Your OfficeOS session is valid and secure.')}catch(e){alert('Your session needs to be refreshed. Please sign in again.');try{await supabaseClient.auth.signOut({scope:'local'})}catch{}el('authGate')?.classList.remove('hidden')}finally{if(btn?.tagName==='BUTTON')btn.disabled=false}}
window.officeForgetThisDevice=async function(){if(!confirm('Forget this device and sign out? You will need to enter your password next time.'))return;localStorage.setItem(REMEMBER_KEY,'0');localStorage.removeItem('officeos_last_email');localStorage.removeItem(SESSION_ONLY_KEY);sessionStorage.clear();try{await supabaseClient.auth.signOut({scope:'local'})}catch{}location.replace(SITE)}
window.officeSendPasswordReset=async function(){const email=window.currentUser?.email||el('accountEmail')?.textContent?.trim();if(!email||!email.includes('@'))return alert('Sign in first.');const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:SITE});if(error)return alert(error.message);alert(`Password reset email sent to ${email}.`)}
const originalSecurity=window.OfficeOSSecurity?.verifySession;
if(originalSecurity){window.OfficeOSSecurity.verifySession=async function(force){const result=await originalSecurity(force);if(result){localStorage.setItem(LAST_VERIFY_KEY,new Date().toISOString());const label=el('officeLastVerify');if(label)label.textContent=stamp()}return result}}
setTimeout(install,1100);
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(install,0);return r};
})();