(function(){
function settings(){db.appSettings=db.appSettings||{};return Object.assign({theme:'system',invoiceDueDays:30,defaultTaxRate:0,autoOverdue:true,confirmDeletes:true,compact:false},db.appSettings)}
function applyTheme(){const s=settings(),root=document.documentElement,theme=s.theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):s.theme;root.dataset.theme=theme;document.body.classList.toggle('compact-ui',!!s.compact)}
function settingsCard(){const s=settings();return `<div class="card" id="appSettingsCard"><div class="section-title"><div><div class="kicker">Preferences</div><h2>App Settings</h2></div></div><p class="muted">Change how OfficeOS looks and behaves for this account.</p><label>Appearance</label><select id="setTheme"><option value="system" ${s.theme==='system'?'selected':''}>Use device setting</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option><option value="dark" ${s.theme==='dark'?'selected':''}>Dark</option></select><div class="settings-grid"><div><label>Default Invoice Due</label><select id="setDue"><option value="0" ${s.invoiceDueDays===0?'selected':''}>Due immediately</option><option value="7" ${s.invoiceDueDays===7?'selected':''}>Net 7</option><option value="15" ${s.invoiceDueDays===15?'selected':''}>Net 15</option><option value="30" ${s.invoiceDueDays===30?'selected':''}>Net 30</option><option value="45" ${s.invoiceDueDays===45?'selected':''}>Net 45</option><option value="60" ${s.invoiceDueDays===60?'selected':''}>Net 60</option></select></div><div><label>Default Tax %</label><input id="setTax" type="number" step="0.01" min="0" value="${Number(s.defaultTaxRate||0)}"></div></div><label class="setting-toggle"><input id="setAutoOverdue" type="checkbox" ${s.autoOverdue?'checked':''}><span><b>Automatically mark overdue invoices</b><small>Changes sent/open invoices to Overdue after the due date.</small></span></label><label class="setting-toggle"><input id="setConfirmDeletes" type="checkbox" ${s.confirmDeletes?'checked':''}><span><b>Confirm before deleting</b><small>Helps prevent accidental deletions.</small></span></label><label class="setting-toggle"><input id="setCompact" type="checkbox" ${s.compact?'checked':''}><span><b>Compact layout</b><small>Fits more information on screen.</small></span></label><button class="primary full" onclick="saveAppSettings()">Save App Settings</button></div>`}
window.saveAppSettings=function(){db.appSettings={...settings(),theme:document.getElementById('setTheme').value,invoiceDueDays:Number(document.getElementById('setDue').value),defaultTaxRate:Number(document.getElementById('setTax').value||0),autoOverdue:document.getElementById('setAutoOverdue').checked,confirmDeletes:document.getElementById('setConfirmDeletes').checked,compact:document.getElementById('setCompact').checked};applyTheme();logActivity(current()==='all'?(db.companies[0]?.id||''):current(),'Updated app settings');save();alert('App settings saved.')}
window.officeSettings=settings;
const oldRenderOffice=window.renderOffice;window.renderOffice=function(){const r=oldRenderOffice.apply(this,arguments);const more=document.getElementById('more'),account=more?.querySelector('.card');if(more&&!document.getElementById('appSettingsCard')&&account)account.insertAdjacentHTML('afterend',settingsCard());return r}
const oldOpenForm=window.openForm;window.openForm=function(type,data=null){const r=oldOpenForm(type,data);if(type==='invoice'&&!data)setTimeout(()=>{const s=settings(),issue=document.getElementById('fIssueDate'),due=document.getElementById('fDueDate'),tax=document.getElementById('fTaxRate');if(issue&&due&&issue.value){const d=new Date(issue.value+'T12:00:00');d.setDate(d.getDate()+Number(s.invoiceDueDays||0));due.value=d.toISOString().slice(0,10)}if(tax){tax.value=Number(s.defaultTaxRate||0);window.invoiceRecalc?.()}},0);return r}
if(matchMedia)matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(settings().theme==='system')applyTheme()});applyTheme();
})();