(function(){
const $m=id=>document.getElementById(id);
const FIELD_PERMS=[['jobs.status','Update job status'],['jobs.checklist','Complete checklist items'],['jobs.field_notes','Add field notes'],['files.upload_assigned','Upload job photos/files']];
function escM(v){return typeof esc==='function'?esc(v):String(v??'')}
function ensure(){db.teamMembers=Array.isArray(db.teamMembers)?db.teamMembers:[];for(const m of db.teamMembers){if(!Array.isArray(m.permissions))m.permissions=[];if(!Array.isArray(m.deniedPermissions))m.deniedPermissions=[]}for(const j of db.jobs||[])if(!Array.isArray(j.assignedTeamIds))j.assignedTeamIds=[]}
function currentCompanyId(){return typeof current==='function'&&current()!=='all'?current():(db.companies?.[0]?.id||'')}
function currentCompanyName(){return(db.companies||[]).find(c=>c.id===currentCompanyId())?.name||'Company'}
function roleLabel(role){return window.OfficeOSField?.ROLE_DEFAULTS?.[role]?.label||role}
function members(){ensure();const cid=currentCompanyId();return db.teamMembers.filter(m=>m.company===cid||m.companyId===cid)}
function addDraft(){ensure();const cid=currentCompanyId(),name=$m('teamName')?.value.trim(),email=$m('teamEmail')?.value.trim().toLowerCase(),role=$m('teamRole')?.value||'field';if(!cid||!name||!email)return alert('Enter the employee name and email.');if(db.teamMembers.some(m=>(m.company===cid||m.companyId===cid)&&String(m.email||'').toLowerCase()===email))return alert('That email is already on this team.');db.teamMembers.push({id:uid(),company:cid,companyId:cid,name,email,role,permissions:[],deniedPermissions:[],userId:'',active:true,inviteStatus:'pending',createdAt:nowISO(),updatedAt:nowISO()});logActivity(cid,`Added ${name} to Team & Permissions (invitation pending)`);save();if($m('teamName'))$m('teamName').value='';if($m('teamEmail'))$m('teamEmail').value='';render();}
function changeRole(id,role){const m=db.teamMembers.find(x=>x.id===id);if(!m)return;m.role=role;m.permissions=[];m.deniedPermissions=[];m.updatedAt=nowISO();logActivity(m.company||m.companyId,`Changed ${m.name} role to ${roleLabel(role)}`);save();render()}
function toggleActive(id){const m=db.teamMembers.find(x=>x.id===id);if(!m)return;m.active=m.active===false?true:false;m.updatedAt=nowISO();logActivity(m.company||m.companyId,`${m.active?'Enabled':'Disabled'} team member ${m.name}`);save();render()}
function hasPerm(m,p){return window.OfficeOSField?.can?.(p,m)===true}
function setPermission(id,p,enabled){ensure();const m=db.teamMembers.find(x=>x.id===id);if(!m)return;const base=new Set(window.OfficeOSField?.ROLE_DEFAULTS?.[m.role]?.permissions||[]);m.permissions=m.permissions.filter(x=>x!==p);m.deniedPermissions=m.deniedPermissions.filter(x=>x!==p);if(enabled&&!base.has(p))m.permissions.push(p);if(!enabled&&base.has(p))m.deniedPermissions.push(p);m.updatedAt=nowISO();logActivity(m.company||m.companyId,`Updated field permissions for ${m.name}`);save();render()}
function permissionEditor(m){if(!['field','sales'].includes(m.role))return'';return `<details class="team-permission-editor"><summary>Customize field access</summary><div class="team-permission-grid">${FIELD_PERMS.map(([p,label])=>`<label><input type="checkbox" ${hasPerm(m,p)?'checked':''} onchange="officeTeamPermission('${m.id}','${p}',this.checked)"><span>${escM(label)}</span></label>`).join('')}</div><div class="tiny">These permissions only add/remove allowed field actions. Pricing, invoices, accounting, billing, company settings, permissions and protected deletion remain locked for field roles.</div></details>`}
function memberCards(){const a=members();if(!a.length)return'<div class="empty">No team members have been added yet.</div>';return a.map(m=>`<div class="team-member ${m.active===false?'disabled':''}"><div class="team-member-main"><div class="team-avatar">${escM((m.name||'?').charAt(0).toUpperCase())}</div><div><b>${escM(m.name)}</b><div class="muted">${escM(m.email)}</div><div class="team-state">${m.userId?'Account linked':'Invitation not sent yet'} · ${m.active===false?'Disabled':'Active'}</div></div></div><div class="team-member-controls"><select onchange="officeTeamRole('${m.id}',this.value)"><option value="office_manager" ${m.role==='office_manager'?'selected':''}>Office Manager</option><option value="sales" ${m.role==='sales'?'selected':''}>Sales</option><option value="field" ${m.role==='field'?'selected':''}>Field Employee / Contractor</option></select><button class="${m.active===false?'success':'secondary'}" onclick="officeTeamToggle('${m.id}')">${m.active===false?'Enable':'Disable'}</button></div>${permissionEditor(m)}</div>`).join('')}
function upcomingJobs(){const cid=currentCompanyId(),today=new Date().toISOString().slice(0,10);return(db.jobs||[]).filter(j=>j.company===cid&&!['Complete','Cancelled'].includes(j.status)&&(j.date||'9999-99-99')>=today).sort((a,b)=>((a.date||'')+(a.time||'')).localeCompare((b.date||'')+(b.time||''))).slice(0,20)}
function assignments(){const ms=members().filter(m=>m.active!==false),jobs=upcomingJobs();if(!jobs.length)return'<div class="empty">No upcoming jobs to assign.</div>';if(!ms.length)return'<div class="empty">Add a team member before assigning jobs.</div>';return jobs.map(j=>`<div class="team-job"><div><b>${escM(j.title||j.customer||'Job')}</b><div class="muted">${escM(j.date||'Unscheduled')}${j.time?' · '+escM(j.time):''}${j.customer?' · '+escM(j.customer):''}</div></div><div class="team-assignees">${ms.map(m=>`<label><input type="checkbox" ${j.assignedTeamIds?.includes(m.id)?'checked':''} onchange="officeAssignTeam('${j.id}','${m.id}',this.checked)"><span>${escM(m.name)}</span></label>`).join('')}</div></div>`).join('')}
function assign(jobId,memberId,checked){ensure();const job=db.jobs.find(x=>x.id===jobId),m=db.teamMembers.find(x=>x.id===memberId);if(!job||!m)return;const set=new Set(job.assignedTeamIds||[]);checked?set.add(memberId):set.delete(memberId);job.assignedTeamIds=[...set];job.updatedAt=nowISO();logActivity(job.company,`${checked?'Assigned':'Unassigned'} ${m.name} ${checked?'to':'from'} ${job.title||job.customer||'job'}`);save();render()}
function render(){if($m('teamMemberList'))$m('teamMemberList').innerHTML=memberCards();if($m('teamAssignmentList'))$m('teamAssignmentList').innerHTML=assignments();if($m('teamCompanyName'))$m('teamCompanyName').textContent=currentCompanyName()}
function install(){if($m('teamPermissionsCard'))return;ensure();const office=$m('more');if(!office)return;const card=document.createElement('div');card.className='card';card.id='teamPermissionsCard';card.innerHTML=`<div class="section-title"><div><div class="kicker">People & Access</div><h2>Team & Permissions</h2></div></div><p class="muted">Employees get their own limited workspace. Important business controls stay locked unless their role explicitly allows them.</p><div class="team-security-note"><b>Secure invitations are not live on production yet.</b><span>You can build the team and assignments here in the 1.0 branch. The invitation backend will link each employee's real login after the membership migration is validated.</span></div><div class="team-add-grid"><div><label>Name</label><input id="teamName" placeholder="Employee name"></div><div><label>Email</label><input id="teamEmail" type="email" placeholder="employee@example.com"></div><div><label>Role</label><select id="teamRole"><option value="field">Field Employee / Contractor</option><option value="sales">Sales</option><option value="office_manager">Office Manager</option></select></div></div><button class="primary full" onclick="officeTeamAddDraft()">Add to Team Setup</button><h3>Team for <span id="teamCompanyName"></span></h3><div id="teamMemberList"></div><div class="team-permission-summary"><b>Field employees can</b><span>See assigned jobs, job packets, approved customer details, checklists and files; update allowed job status; add field notes and work photos.</span><b>Field employees cannot</b><span>Change pricing, invoices, payments, master customer records, master templates, settings, accounting, reports, billing, permissions or delete protected records.</span></div><h3>Assign Upcoming Jobs</h3><div id="teamAssignmentList"></div>`;const template=$m('jobTemplateLibrary');template?.parentElement?.insertBefore(card,template);render()}
window.officeTeamAddDraft=addDraft;window.officeTeamRole=changeRole;window.officeTeamToggle=toggleActive;window.officeTeamPermission=setPermission;window.officeAssignTeam=assign;window.officeRenderTeamAdmin=render;setTimeout(install,1350);
})();