(function(){
'use strict';
const el=id=>document.getElementById(id);
const esc2=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let secure={company:null,members:[],invites:[],loading:false,lastCompanyRef:''};
function ensure(){db.teamMembers=Array.isArray(db.teamMembers)?db.teamMembers:[];for(const j of db.jobs||[])if(!Array.isArray(j.assignedTeamIds))j.assignedTeamIds=[]}
function legacyCompany(){const id=typeof current==='function'?current():'all';if(id==='all')return null;return(db.companies||[]).find(c=>c.id===id)||null}
function roleLabel(role){return role==='field'?'Field Employee / Installer':role==='sales'?'Sales / Estimator':role==='office_manager'?'Office Manager':'Team Member'}
function localMemberByEmail(email,cid){const e=String(email||'').toLowerCase();return(db.teamMembers||[]).find(m=>(m.company===cid||m.companyId===cid)&&String(m.email||'').toLowerCase()===e)}
async function normalizedCompany(c){if(!c||!currentUser)return null;const {data,error}=await supabaseClient.from('companies').select('id,name,external_ref,owner_id').eq('owner_id',currentUser.id).eq('external_ref',String(c.id)).maybeSingle();if(error){console.warn('[OfficeOS] secure company lookup',error);return null}return data||null}
async function refreshSecureTeam(){ensure();const c=legacyCompany(),host=el('teamAccessCenter');if(!host)return;if(!c){host.innerHTML='<div class="card"><div class="empty">Choose one company above to manage its team access.</div></div>';return}secure.loading=true;secure.lastCompanyRef=c.id;render();try{const company=await normalizedCompany(c);secure.company=company;secure.members=[];secure.invites=[];if(company){const [m,i]=await Promise.all([supabaseClient.from('company_memberships').select('id,user_id,role,active,permissions,denied_permissions,created_at').eq('company_id',company.id).order('created_at'),supabaseClient.from('company_invites').select('id,email,role,status,expires_at,accepted_by,created_at').eq('company_id',company.id).order('created_at',{ascending:false})]);if(m.error)throw m.error;if(i.error)throw i.error;secure.members=m.data||[];secure.invites=i.data||[];let changed=false;for(const inv of secure.invites){const local=localMemberByEmail(inv.email,c.id);if(local){if(inv.accepted_by&&local.userId!==inv.accepted_by){local.userId=inv.accepted_by;changed=true}if(local.inviteStatus!==inv.status){local.inviteStatus=inv.status;changed=true}const mem=secure.members.find(x=>x.user_id===inv.accepted_by);if(mem&&local.active!==mem.active){local.active=mem.active;changed=true}}}if(changed){localStorage.setItem(KEY,JSON.stringify(db));cloudSave?.()}}}catch(e){console.error(e);secure.error=e?.message||'Could not load team access.'}finally{secure.loading=false;render()}}
function memberEmail(m){const inv=secure.invites.find(i=>i.accepted_by===m.user_id)||null;return inv?.email||''}
function memberCards(){const c=legacyCompany();if(!secure.company)return'<div class="empty">No secure team has been created for this company yet. Invite the first field employee below.</div>';const rows=secure.members.filter(m=>m.role!=='owner');if(!rows.length)return'<div class="empty">No linked team members yet.</div>';return rows.map(m=>{const email=memberEmail(m),local=email?localMemberByEmail(email,c.id):null;return `<div class="team-access-member"><div class="team-access-avatar">${esc2((local?.name||email||'?').charAt(0).toUpperCase())}</div><div class="team-access-copy"><b>${esc2(local?.name||email||'Team member')}</b><div class="muted">${esc2(email||'OfficeOS account')} · ${esc2(roleLabel(m.role))}</div><div class="team-access-state"><span class="team-dot ${m.active?'on':'off'}"></span>${m.active?'Access active':'Access disabled'}</div></div><button class="secondary team-access-toggle" onclick="officeTeamSecureToggle('${m.id}',${m.active?'false':'true'})">${m.active?'Disable':'Enable'}</button></div>`}).join('')}
function pendingCards(){const pending=secure.invites.filter(i=>i.status==='pending');if(!pending.length)return'';return `<div class="team-pending"><div class="kicker">Pending invitations</div>${pending.map(i=>`<div class="team-pending-row"><div><b>${esc2(i.email)}</b><div class="muted">${esc2(roleLabel(i.role))} · expires ${new Date(i.expires_at).toLocaleDateString()}</div></div><span class="tag">Pending</span></div>`).join('')}</div>`}
function assignmentRows(){const c=legacyCompany();if(!c)return'';const linked=(db.teamMembers||[]).filter(m=>(m.company===c.id||m.companyId===c.id)&&m.active!==false&&m.userId);const today=new Date().toISOString().slice(0,10),jobs=(db.jobs||[]).filter(j=>j.company===c.id&&!['Complete','Cancelled'].includes(j.status)&&(j.date||'9999-99-99')>=today).sort((a,b)=>((a.date||'')+(a.time||'')).localeCompare((b.date||'')+(b.time||''))).slice(0,15);if(!jobs.length)return'<div class="empty">No upcoming jobs to assign.</div>';if(!linked.length)return'<div class="empty">Once an invited employee is linked, you can assign upcoming jobs here.</div>';return jobs.map(j=>`<div class="team-job-row"><div><b>${esc2(j.title||j.customer||'Job')}</b><div class="muted">${esc2(j.date||'Unscheduled')}${j.time?' · '+esc2(j.time):''}${j.customer?' · '+esc2(j.customer):''}</div></div><div class="team-job-people">${linked.map(m=>`<label><input type="checkbox" ${j.assignedTeamIds.includes(m.id)?'checked':''} onchange="officeAssignSecureTeam('${j.id}','${m.id}',this.checked)"><span>${esc2(m.name||m.email)}</span></label>`).join('')}</div></div>`).join('')}
function render(){const host=el('teamAccessCenter');if(!host)return;const c=legacyCompany();host.innerHTML=`<div class="card team-access-card"><div class="row between"><div><div class="kicker">People & Access</div><h2>Team Access</h2></div><button class="secondary" onclick="officeRefreshSecureTeam()">${secure.loading?'Loading…':'Refresh'}</button></div><p class="muted">Invite field staff to their own limited My Day workspace. They only receive jobs assigned to them.</p>${c?`<div class="team-invite-grid"><div><label>Name</label><input id="secureTeamName" placeholder="Employee name"></div><div><label>Email</label><input id="secureTeamEmail" type="email" placeholder="employee@example.com"></div><div><label>Role</label><select id="secureTeamRole"><option value="field">Field Employee / Installer</option><option value="sales">Sales / Estimator</option></select></div></div><button id="secureInviteBtn" class="primary full" onclick="officeSendSecureTeamInvite()">Send Secure Invite</button>`:'<div class="empty">Choose a company above to invite team members.</div>'}${secure.error?`<div class="warning" style="margin-top:10px">${esc2(secure.error)}</div>`:''}<div class="team-linked-list"><h3>Linked Team</h3>${secure.loading?'<div class="muted">Loading secure access…</div>':memberCards()}${pendingCards()}</div><div class="team-access-note"><b>Field access stays limited.</b><span>Assigned jobs, customer contact needed for the job, checklist, status and job photos are available. Pricing, invoices, accounting, payroll, settings and company-wide records stay protected.</span></div><h3>Assign Upcoming Jobs</h3><div id="secureAssignmentList">${assignmentRows()}</div></div>`}
async function sendInvite(){const c=legacyCompany();if(!c)return alert('Choose a company first.');const name=el('secureTeamName')?.value.trim(),email=el('secureTeamEmail')?.value.trim().toLowerCase(),role=el('secureTeamRole')?.value||'field';if(!name||!email||!email.includes('@'))return alert('Enter the employee name and email.');const btn=el('secureInviteBtn');if(btn){btn.disabled=true;btn.textContent='Sending Invite…'}try{const {data,error}=await supabaseClient.functions.invoke('officeos-team-invite',{body:{companyRef:String(c.id),email,role}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Invitation failed.');let local=localMemberByEmail(email,c.id);if(!local){local={id:uid(),company:c.id,companyId:c.id,name,email,role,permissions:[],deniedPermissions:[],userId:'',active:true,inviteStatus:data.status==='linked'?'accepted':'pending',createdAt:nowISO(),updatedAt:nowISO()};db.teamMembers.unshift(local)}else{Object.assign(local,{name,email,role,active:true,inviteStatus:data.status==='linked'?'accepted':'pending',updatedAt:nowISO()})}logActivity(c.id,`${data.status==='linked'?'Linked':'Invited'} ${name} as ${roleLabel(role)}`);localStorage.setItem(KEY,JSON.stringify(db));await cloudSave();await refreshSecureTeam();alert(data.message||'Team invitation sent.')}catch(e){console.error(e);alert(e?.message||'Could not send the invitation.')}finally{if(btn){btn.disabled=false;btn.textContent='Send Secure Invite'}}}
async function toggleMembership(id,active){try{const {error}=await supabaseClient.from('company_memberships').update({active}).eq('id',id);if(error)throw error;const m=secure.members.find(x=>x.id===id);if(m)m.active=active;const email=m?memberEmail(m):'';const local=email?localMemberByEmail(email,legacyCompany()?.id):null;if(local)local.active=active;if(local){localStorage.setItem(KEY,JSON.stringify(db));cloudSave?.()}render()}catch(e){alert(e?.message||'Could not update team access.')}}
async function syncFieldJob(jobId){try{const {data,error}=await supabaseClient.functions.invoke('officeos-sync-field-job',{body:{jobRef:jobId}});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Could not sync job assignment.');return data}catch(e){console.error('[OfficeOS] field job sync',e);throw e}}
async function assign(jobId,memberId,checked){ensure();const job=(db.jobs||[]).find(j=>j.id===jobId),member=(db.teamMembers||[]).find(m=>m.id===memberId);if(!job||!member)return;const set=new Set(job.assignedTeamIds||[]);checked?set.add(memberId):set.delete(memberId);job.assignedTeamIds=[...set];job.updatedAt=nowISO();logActivity(job.company,`${checked?'Assigned':'Unassigned'} ${member.name||member.email} ${checked?'to':'from'} ${job.title||job.customer||'job'}`);localStorage.setItem(KEY,JSON.stringify(db));render?.();await cloudSave();try{await syncFieldJob(jobId)}catch(e){alert('The local assignment was saved, but the employee workspace could not be synced yet. '+(e?.message||''))}render()}
function mount(){ensure();const section=el('teamPayrollSection');if(!section)return;if(!el('teamAccessCenter')){const host=document.createElement('div');host.id='teamAccessCenter';const payroll=el('payrollCenter');if(payroll)section.insertBefore(host,payroll);else section.appendChild(host)}render();setTimeout(refreshSecureTeam,50);window.refreshOfficeOrganization?.()}
window.officeSendSecureTeamInvite=sendInvite;window.officeRefreshSecureTeam=refreshSecureTeam;window.officeTeamSecureToggle=toggleMembership;window.officeAssignSecureTeam=assign;window.officeSyncFieldJob=syncFieldJob;
document.getElementById('companySelect')?.addEventListener('change',()=>setTimeout(()=>{secure.error='';mount();refreshSecureTeam()},80));
setTimeout(mount,1750);setInterval(()=>{if(el('teamPayrollSection')&&!el('teamAccessCenter'))mount()},2500);
})();