(function(){
'use strict';
const ENDPOINT='https://bowrytgqbunodtmzvabp.supabase.co/functions/v1/officeos-terminal';
const el=id=>document.getElementById(id);let pollTimer=null,active=null;
async function call(body){const {data:{session},error}=await supabaseClient.auth.getSession();if(error||!session?.access_token)throw new Error('Please sign in again.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token,'apikey':SUPABASE_KEY},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'Terminal request failed.');return d}
function ctx(){return window.officeWalletCurrent?.()||null}
function box(){return el('walletBody')}
function escx(v){return typeof esc==='function'?esc(v):String(v??'')}
window.officeTerminalOpen=async function(){const c=ctx();if(!c)return alert('Open an invoice first.');clearInterval(pollTimer);active=null;const b=box();b.innerHTML='<div class="empty">Checking card readers…</div>';try{const d=await call({action:'list_readers',companyRef:c.companyRef});renderReaders(d)}catch(e){b.innerHTML=`<div class="empty">${escx(e.message)}</div>`}}
function renderReaders(d){const c=ctx(),b=box();if(!c||!b)return;if(!d.location){b.innerHTML=`<div class="terminal-setup"><div class="item"><b>Set up in-person card payments</b><div class="muted">Create the business Terminal location, then pair a compatible Stripe reader.</div></div><label>Location Name</label><input id="terminalLocationName" value="${escx((db.companies||[]).find(x=>x.id===c.companyRef)?.name||'Main Location')}"><label>Street Address</label><input id="terminalLine1"><label>City</label><input id="terminalCity"><div class="row"><div style="flex:1"><label>State</label><input id="terminalState" value="OH"></div><div style="flex:1"><label>ZIP</label><input id="terminalPostal"></div></div><input id="terminalCountry" type="hidden" value="US"><button class="primary full" onclick="officeTerminalCreateLocation()">Create Card Reader Location</button></div>`;return}
 if(!d.readers?.length){b.innerHTML=`<div class="terminal-setup"><div class="item"><b>${escx(d.location.name||'Card Reader Location')}</b><div class="muted">No readers paired yet.</div></div><label>Reader Pairing Code</label><input id="terminalPairCode" placeholder="Enter code shown on reader"><label>Reader Name</label><input id="terminalReaderLabel" value="OfficeOS Reader"><div class="muted" style="font-size:12px;margin:8px 0">Generate a pairing code from the reader settings, then enter it here.</div><button class="primary full" onclick="officeTerminalRegisterReader()">Pair Reader</button></div>`;return}
 const bal=typeof window.officeInvoiceBalance==='function'?window.officeInvoiceBalance(c.invoice):Math.max(0,Number(c.invoice.balanceDue??c.invoice.amount||0));b.innerHTML=`<label>Amount to Charge</label><input id="terminalAmount" type="number" min="0.01" step="0.01" value="${bal.toFixed(2)}"><label>Card Reader</label><div class="terminal-reader-list">${d.readers.map(r=>`<button class="terminal-reader ${r.id===d.defaultReaderId?'selected':''}" onclick="officeTerminalCharge('${r.id}')"><span><b>${escx(r.label||'Reader')}</b><small>${escx(r.deviceType||'Stripe Reader')} · ${escx(r.status||'unknown')}</small></span><strong>${r.status==='online'?'Charge':'Offline'}</strong></button>`).join('')}</div><button class="secondary full" onclick="officeTerminalShowPair()">+ Pair another reader</button><div id="terminalStatus" class="terminal-status"></div>`}
window.officeTerminalCreateLocation=async function(){const c=ctx();if(!c)return;const btn=[...box().querySelectorAll('button')].find(x=>/create card reader/i.test(x.textContent||''));if(btn){btn.disabled=true;btn.textContent='Creating…'}try{await call({action:'setup_location',companyRef:c.companyRef,locationName:el('terminalLocationName').value.trim(),address:{line1:el('terminalLine1').value.trim(),city:el('terminalCity').value.trim(),state:el('terminalState').value.trim(),postal_code:el('terminalPostal').value.trim(),country:el('terminalCountry').value}});await officeTerminalOpen()}catch(e){alert(e.message);if(btn){btn.disabled=false;btn.textContent='Create Card Reader Location'}}}
window.officeTerminalShowPair=function(){const c=ctx(),b=box();if(!c||!b)return;b.innerHTML=`<div class="item"><b>Pair a Stripe reader</b><div class="muted">Open the reader settings and generate a pairing code.</div></div><label>Reader Pairing Code</label><input id="terminalPairCode" placeholder="Pairing code"><label>Reader Name</label><input id="terminalReaderLabel" value="OfficeOS Reader"><button class="primary full" onclick="officeTerminalRegisterReader()">Pair Reader</button><button class="secondary full" onclick="officeTerminalOpen()">Back</button>`}
window.officeTerminalRegisterReader=async function(){const c=ctx();if(!c)return;const code=el('terminalPairCode')?.value.trim();if(!code)return alert('Enter the pairing code shown on the reader.');const btn=[...box().querySelectorAll('button')].find(x=>/pair reader/i.test(x.textContent||''));if(btn){btn.disabled=true;btn.textContent='Pairing…'}try{await call({action:'register_reader',companyRef:c.companyRef,registrationCode:code,label:el('terminalReaderLabel')?.value.trim()||'OfficeOS Reader'});await officeTerminalOpen()}catch(e){alert(e.message);if(btn){btn.disabled=false;btn.textContent='Pair Reader'}}}
window.officeTerminalCharge=async function(readerId){const c=ctx();if(!c)return;const amount=Number(el('terminalAmount')?.value||0);if(!amount||amount<=0)return alert('Enter an amount to charge.');if(!confirm(`Send ${money(amount)} to the card reader?`))return;const status=el('terminalStatus');if(status)status.innerHTML='<div class="terminal-working">Waiting for customer to tap, insert, or swipe card…</div>';try{const d=await call({action:'start_payment',companyRef:c.companyRef,invoiceRef:c.invoice.id,amount,readerId});active={companyRef:c.companyRef,invoiceRef:c.invoice.id,paymentIntentId:d.paymentIntentId,readerId:d.readerId,amount:d.amount};poll(active);clearInterval(pollTimer);pollTimer=setInterval(()=>poll(active),1800)}catch(e){if(status)status.innerHTML=`<div class="terminal-error">${escx(e.message)}</div>`}}
async function poll(a){if(!a)return;try{const d=await call({action:'payment_status',companyRef:a.companyRef,invoiceRef:a.invoiceRef,paymentIntentId:a.paymentIntentId,readerId:a.readerId}),status=el('terminalStatus');if(!status)return;if(d.status==='succeeded'){clearInterval(pollTimer);pollTimer=null;status.innerHTML=`<div class="terminal-success"><b>Payment approved ✓</b><span>${money(d.amount)} received by card.</span></div>`;try{await window.officeSyncInvoicePayments?.(a.invoiceRef);logActivity(a.companyRef,`Received ${money(d.amount)} in-person card payment`);save();render();window.renderAccounting?.();const p=(db.paymentLedger||[]).filter(x=>x.invoiceRef===a.invoiceRef&&(x.providerPaymentId===a.paymentIntentId||x.provider_payment_id===a.paymentIntentId)).sort((x,y)=>String(y.paidAt||'').localeCompare(String(x.paidAt||'')))[0];await window.officeShowPaymentSuccess?.({invoiceId:a.invoiceRef,paymentId:p?.id,amount:d.amount,method:'Card Present',providerPaymentId:a.paymentIntentId})}catch{}return}if(d.reader?.actionStatus==='failed'||['canceled'].includes(d.status)){clearInterval(pollTimer);pollTimer=null;status.innerHTML=`<div class="terminal-error"><b>Payment not completed</b><span>${escx(d.reader?.failureMessage||'Try the card again or choose another payment method.')}</span></div><button class="secondary full" onclick="officeTerminalOpen()">Try Again</button>`;return}status.innerHTML=`<div class="terminal-working"><b>Reader is ready</b><span>${d.reader?.actionStatus==='in_progress'?'Waiting for card…':'Processing payment…'}</span></div><button class="secondary full" onclick="officeTerminalCancel()">Cancel Payment</button>`}catch(e){console.warn('[OfficeOS Terminal]',e)}}
window.officeTerminalCancel=async function(){if(!active)return;try{await call({action:'cancel_reader',companyRef:active.companyRef,readerId:active.readerId});clearInterval(pollTimer);pollTimer=null;active=null;const s=el('terminalStatus');if(s)s.innerHTML='<div class="empty">Payment canceled.</div>'}catch(e){alert(e.message)}}
})();