const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const tools=[
 {type:"function",name:"create_task",description:"Create a normal internal follow-up task.",parameters:{type:"object",properties:{company:{type:"string"},title:{type:"string"},priority:{type:"string"},dueDate:{type:"string"}},required:["title"],additionalProperties:false}},
 {type:"function",name:"create_event",description:"Schedule an appointment/event when the user explicitly asks and details are known.",parameters:{type:"object",properties:{company:{type:"string"},title:{type:"string"},type:{type:"string"},date:{type:"string"},time:{type:"string"},customer:{type:"string"},address:{type:"string"},notes:{type:"string"}},required:["title","date"],additionalProperties:false}},
 {type:"function",name:"create_customer",description:"Create a customer record.",parameters:{type:"object",properties:{company:{type:"string"},name:{type:"string"},phone:{type:"string"},email:{type:"string"},address:{type:"string"},notes:{type:"string"}},required:["name"],additionalProperties:false}},
 {type:"function",name:"create_lead",description:"Create a lead record.",parameters:{type:"object",properties:{company:{type:"string"},name:{type:"string"},phone:{type:"string"},email:{type:"string"},service:{type:"string"},value:{type:"number"},status:{type:"string"},notes:{type:"string"}},required:["name"],additionalProperties:false}},
 {type:"function",name:"update_lead_status",description:"Update an existing lead stage.",parameters:{type:"object",properties:{id:{type:"string"},status:{type:"string"}},required:["id","status"],additionalProperties:false}},
 {type:"function",name:"mark_task_done",description:"Mark an internal task complete.",parameters:{type:"object",properties:{id:{type:"string"}},required:["id"],additionalProperties:false}},
 {type:"function",name:"request_approval",description:"Use for customer-facing messages, schedule changes/reschedules, overdue payment messages, deposit or invoice edits, unusual customer requests, or any action the company playbook says requires approval. Never execute discounts, refunds, pricing/contract/warranty changes or invoice modifications automatically.",parameters:{type:"object",properties:{company:{type:"string"},title:{type:"string"},detail:{type:"string"}},required:["title","detail"],additionalProperties:false}}
];
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const key=Deno.env.get("OPENAI_API_KEY");if(!key)throw new Error("OPENAI_API_KEY is not configured");const {message,context}=await req.json();const instructions=`You are OfficeOS AI, an operations assistant inside a small-business office app. Use the supplied live OfficeOS context as the source of truth. Be concise and useful. You may create internal customers, leads, tasks and new calendar events, and update lead/task state using tools. Customer-facing communication, schedule changes/reschedules, overdue-payment messages, deposit/invoice edits and unusual requests MUST be prepared for approval. NEVER autonomously give discounts/refunds, change pricing/contracts/warranties, or modify invoices. Respect the selected company's playbook. If asked for information, answer from context without inventing. Current date: ${new Date().toISOString().slice(0,10)}.`;const input=`USER REQUEST:\n${message}\n\nOFFICEOS CONTEXT:\n${JSON.stringify(context)}`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",store:false,instructions,input,tools,tool_choice:"auto"})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||"OpenAI request failed");let text="",actions=[];for(const item of j.output||[]){if(item.type==="message")for(const c of item.content||[])if(c.type==="output_text")text+=c.text;if(item.type==="function_call"){let args={};try{args=JSON.parse(item.arguments||"{}")}catch{};if(item.name==="request_approval")actions.push({name:item.name,args,company:args.company,title:args.title,detail:args.detail,requiresApproval:true});else actions.push({name:item.name,args})}}return new Response(JSON.stringify({message:text||((actions.length)?"I found the right action.":"I couldn't determine an action yet."),actions}),{headers:{...cors,"Content-Type":"application/json"}})}catch(e){return new Response(JSON.stringify({error:e.message}),{status:500,headers:{...cors,"Content-Type":"application/json"}})}});